### ISSUE TITLE
talend soop_trv failing

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#102]
Seems like a file was not uploaded properly:
```
Exception in component iNetCDFGlobalAttributes_1
java.io.FileNotFoundException: /mnt/imos-t3/IMOS/opendap/SOOP/SOOP-TRV/VNCF_Cape-Ferguson/By_Cruise/Cruise_START-20150515T055011Z_END-20150516T025009Z/salinity/IMOS_SOOP-TRV_S_20150515T055011Z_VNCF_FV01_END-20150516T025009Z_C-20150516T200138Z.nc (Permission denied)
        at java.io.RandomAccessFile.open(Native Method)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:241)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:122)
        at ucar.unidata.io.RandomAccessFile.<init>(RandomAccessFile.java:267)
        at ucar.nc2.NetcdfFile.getRaf(NetcdfFile.java:520)
        at ucar.nc2.NetcdfFile.open(NetcdfFile.java:391)
        at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:687)
        at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:424)
        at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:407)
        at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:392)
        at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:379)
        at soop_trv.onefileprocess_0_1.oneFileProcess.iNetCDFGlobalAttributes_1Process(oneFileProcess.java:4228)
        at soop_trv.onefileprocess_0_1.oneFileProcess.tPostgresqlInput_3Process(oneFileProcess.java:1242)
        at soop_trv.onefileprocess_0_1.oneFileProcess.tPostgresqlConnection_1Process(oneFileProcess.java:914)
        at soop_trv.onefileprocess_0_1.oneFileProcess.iIncludeSdiLibraries_1Process(oneFileProcess.java:796)
        at soop_trv.onefileprocess_0_1.oneFileProcess.runJobInTOS(oneFileProcess.java:15441)
        at soop_trv.onefileprocess_0_1.oneFileProcess.runJob(oneFileProcess.java:15296)
        at soop_trv.soop_trv_harvester_0_1.SOOP_TRV_harvester.iHarvestResources_1Process(SOOP_TRV_harvester.java:2449)
        at soop_trv.soop_trv_harvester_0_1.SOOP_TRV_harvester.iPostgresqlDbUpdate_1Process(SOOP_TRV_harvester.java:1755)
        at soop_trv.soop_trv_harvester_0_1.SOOP_TRV_harvester.tRunJob_1Process(SOOP_TRV_harvester.java:1145)
        at soop_trv.soop_trv_harvester_0_1.SOOP_TRV_harvester.runJobInTOS(SOOP_TRV_harvester.java:4446)
        at soop_trv.soop_trv_harvester_0_1.SOOP_TRV_harvester.main(SOOP_TRV_harvester.java:4278)
Exception while processing /mnt/imos-t3/IMOS/opendap/SOOP/SOOP-TRV/VNCF_Cape-Ferguson/By_Cruise/Cruise_START-20150515T055011Z_END-20150516T025009Z/salinity/IMOS_SOOP-TRV_S_20150515T055011Z_VNCF_FV01_END-20150516T025009Z_C-20150516T200138Z.nc
```

The file size is 0 with wrong permissions. Indicating a failed upload that was not verified properly:
```
$ ls -l /mnt/imos-t3/IMOS/opendap/SOOP/SOOP-TRV/VNCF_Cape-Ferguson/By_Cruise/Cruise_START-20150515T055011Z_END-20150516T025009Z/salinity/IMOS_SOOP-TRV_S_20150515T055011Z_VNCF_FV01_END-20150516T025009Z_C-20150516T200138Z.nc
---------- 1 nobody nogroup 0 Sep  1  1973 /mnt/imos-t3/IMOS/opendap/SOOP/SOOP-TRV/VNCF_Cape-Ferguson/By_Cruise/Cruise_START-20150515T055011Z_END-20150516T025009Z/salinity/IMOS_SOOP-TRV_S_20150515T055011Z_VNCF_FV01_END-20150516T025009Z_C-20150516T200138Z.nc
```

**Comment by lbesnard** [comment]
> The file size is 0 with wrong permissions. Indicating a failed upload that was not verified properly:

nop, indicating something else. The data is downloaded by a matlab script. I need to investigate why the files went through all the different checks I already have in place
