### ISSUE TITLE
talend aodn_aims_ctd failing

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#103]
Failed because of:
```
In finally block
Exception in component tMap_1
java.lang.NumberFormatException: empty String
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1020)
        at java.lang.Float.parseFloat(Float.java:452)
        at aodn_aims_ctd.harvest_ctd_data_0_1.Harvest_CTD_data.tFileInputDelimited_1Process(Harvest_CTD_data.java:1990)
        at aodn_aims_ctd.harvest_ctd_data_0_1.Harvest_CTD_data.tPostgresqlRow_1Process(Harvest_CTD_data.java:807)
        at aodn_aims_ctd.harvest_ctd_data_0_1.Harvest_CTD_data.tPostgresqlConnection_1Process(Harvest_CTD_data.java:678)
        at aodn_aims_ctd.harvest_ctd_data_0_1.Harvest_CTD_data.iIncludeSdiLibraries_1Process(Harvest_CTD_data.java:544)
        at aodn_aims_ctd.harvest_ctd_data_0_1.Harvest_CTD_data.runJobInTOS(Harvest_CTD_data.java:3999)
        at aodn_aims_ctd.harvest_ctd_data_0_1.Harvest_CTD_data.runJob(Harvest_CTD_data.java:3842)
        at aodn_aims_ctd.aodn_aims_ctd_harvester_0_1.AODN_AIMS_CTD_harvester.iHarvestResources_2Process(AODN_AIMS_CTD_harvester.java:1830)
        at aodn_aims_ctd.aodn_aims_ctd_harvester_0_1.AODN_AIMS_CTD_harvester.iDeletedResources_1Process(AODN_AIMS_CTD_harvester.java:1611)
        at aodn_aims_ctd.aodn_aims_ctd_harvester_0_1.AODN_AIMS_CTD_harvester.iPostgresqlDbUpdate_1Process(AODN_AIMS_CTD_harvester.java:1277)
        at aodn_aims_ctd.aodn_aims_ctd_harvester_0_1.AODN_AIMS_CTD_harvester.iIndexFiles_1_iFilesProcess(AODN_AIMS_CTD_harvester.java:2576)
        at aodn_aims_ctd.aodn_aims_ctd_harvester_0_1.AODN_AIMS_CTD_harvester.runJobInTOS(AODN_AIMS_CTD_harvester.java:4308)
        at aodn_aims_ctd.aodn_aims_ctd_harvester_0_1.AODN_AIMS_CTD_harvester.main(AODN_AIMS_CTD_harvester.java:4128)
Exception while processing /mnt/imos-t4/IMOS/archive/eMII/TALEND_harvester/AODN/AIMS_CTD/SCTmet01-2.csv
```

**Comment by danfruehauf** [comment]
@lbesnard That's good now. Close?
