### ISSUE TITLE
talend aodn_aims_ctd failing

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#128]
Harvester is failing due to a lack of metadata record in production:
```
Exception in component iUpdateSpatialExtent_1
it.geosolutions.geonetwork.exception.GNServerException: Error retrieving metadata in GeoNetwork
        at it.geosolutions.geonetwork.op.GNMetadataGet.gnGetMetadata(GNMetadataGet.java:82)
        at it.geosolutions.geonetwork.op.GNMetadataGet.get(GNMetadataGet.java:63)
        at it.geosolutions.geonetwork.op.GNMetadataGet.get(GNMetadataGet.java:58)
        at it.geosolutions.geonetwork.GNClient.get(GNClient.java:122)
        at aodn_aims_ctd.updatemetadata_0_1.UpdateMetadata.iUpdateSpatialExtent_1Process(UpdateMetadata.java:525)
        at aodn_aims_ctd.updatemetadata_0_1.UpdateMetadata.runJobInTOS(UpdateMetadata.java:806)
        at aodn_aims_ctd.updatemetadata_0_1.UpdateMetadata.runJob(UpdateMetadata.java:653)
        at aodn_aims_ctd.aodn_aims_ctd_harvester_0_1.AODN_AIMS_CTD_harvester.tRunJob_4Process(AODN_AIMS_CTD_harvester.java:2406)
        at aodn_aims_ctd.aodn_aims_ctd_harvester_0_1.AODN_AIMS_CTD_harvester.tPostgresqlRow_1Process(AODN_AIMS_CTD_harvester.java:2288)
        at aodn_aims_ctd.aodn_aims_ctd_harvester_0_1.AODN_AIMS_CTD_harvester.iHarvestResources_2Process(AODN_AIMS_CTD_harvester.java:2130)
        at aodn_aims_ctd.aodn_aims_ctd_harvester_0_1.AODN_AIMS_CTD_harvester.iDeletedResources_1Process(AODN_AIMS_CTD_harvester.java:1771)
        at aodn_aims_ctd.aodn_aims_ctd_harvester_0_1.AODN_AIMS_CTD_harvester.iPostgresqlDbUpdate_1Process(AODN_AIMS_CTD_harvester.java:1430)
        at aodn_aims_ctd.aodn_aims_ctd_harvester_0_1.AODN_AIMS_CTD_harvester.iIndexFiles_1_iFilesProcess(AODN_AIMS_CTD_harvester.java:3071)
        at aodn_aims_ctd.aodn_aims_ctd_harvester_0_1.AODN_AIMS_CTD_harvester.runJobInTOS(AODN_AIMS_CTD_harvester.java:4831)
        at aodn_aims_ctd.aodn_aims_ctd_harvester_0_1.AODN_AIMS_CTD_harvester.main(AODN_AIMS_CTD_harvester.java:4623)
Exception in component tRunJob_4
java.lang.RuntimeException: Child job running failed
        at aodn_aims_ctd.aodn_aims_ctd_harvester_0_1.AODN_AIMS_CTD_harvester.tRunJob_4Process(AODN_AIMS_CTD_harvester.java:2417)
        at aodn_aims_ctd.aodn_aims_ctd_harvester_0_1.AODN_AIMS_CTD_harvester.tPostgresqlRow_1Process(AODN_AIMS_CTD_harvester.java:2288)
        at aodn_aims_ctd.aodn_aims_ctd_harvester_0_1.AODN_AIMS_CTD_harvester.iHarvestResources_2Process(AODN_AIMS_CTD_harvester.java:2130)
        at aodn_aims_ctd.aodn_aims_ctd_harvester_0_1.AODN_AIMS_CTD_harvester.iDeletedResources_1Process(AODN_AIMS_CTD_harvester.java:1771)
        at aodn_aims_ctd.aodn_aims_ctd_harvester_0_1.AODN_AIMS_CTD_harvester.iPostgresqlDbUpdate_1Process(AODN_AIMS_CTD_harvester.java:1430)
        at aodn_aims_ctd.aodn_aims_ctd_harvester_0_1.AODN_AIMS_CTD_harvester.iIndexFiles_1_iFilesProcess(AODN_AIMS_CTD_harvester.java:3071)
        at aodn_aims_ctd.aodn_aims_ctd_harvester_0_1.AODN_AIMS_CTD_harvester.runJobInTOS(AODN_AIMS_CTD_harvester.java:4831)
        at aodn_aims_ctd.aodn_aims_ctd_harvester_0_1.AODN_AIMS_CTD_harvester.main(AODN_AIMS_CTD_harvester.java:4623)
```

Quite likely that I'll stop it from running in production since it has been like that for a while.

**Comment by smancini** [comment]
Our current plan is to make this layer available on portal-rc.
Then we will contact AIMS (hopefully this week) for their feedbacks/comments and finally publish it in production.

**Comment by danfruehauf** [comment]
@smancini All good. It's here to remind us why it's failing. What is the estimated time line for that?

**Comment by bpasquer** [comment]
the harvester has to be redeployed cause of changes merged last friday. Once it's running it is probably ready  to be presented to AIMS people.  Estimated time line for feedback is unknown.

**Comment by danfruehauf** [comment]
If we don't have an estimate, we might as well remove it from running in production.

**Comment by bpasquer** [comment]
Happy with that, it wasn’t suppose to go beyond rc anyway at this stage

On 17 Aug 2015, at 4:18 pm, Dan Fruehauf <notifications@github.com<mailto:notifications@github.com>> wrote:


If we don't have an estimate, we might as well remove it from running in production.

—
Reply to this email directly or view it on GitHub<https://github.com/aodn/content/issues/128#issuecomment-131691973>.

Dr. Benedicte Pasquer - Project Officer
Monday - Friday 9am -3pm
IMOS e-Marine Information Infrastructure
University of Tasmania
Ph: +61 3 6226 1927













University of Tasmania Electronic Communications Policy (December, 2014).
This email is confidential, and is for the intended recipient only. Access, disclosure, copying, distribution, or reliance on any of it by anyone outside the intended recipient organisation is prohibited and may be a criminal offence. Please delete if obtained in error and email confirmation to the sender. The views expressed in this email are not necessarily the views of the University of Tasmania, unless clearly intended otherwise.

**Comment by danfruehauf** [comment]
Bump.

@ggalibert pushed that again to prod. So that's a problem.

**Comment by bpasquer** [comment]
@danfruehauf yes he did because i asked him to. I needed to get a schema dump from prod.

**Comment by danfruehauf** [comment]
You know that it's preventing beer from @lbesnard, yeah??

**Comment by bpasquer** [comment]
Yes but he’ll get chocolate instead.

On 9 Sep 2015, at 11:17 am, Dan Fruehauf <notifications@github.com<mailto:notifications@github.com>> wrote:


You know that it's preventing beer from @lbesnard<https://github.com/lbesnard>, yeah??

—
Reply to this email directly or view it on GitHub<https://github.com/aodn/content/issues/128#issuecomment-138744935>.

Dr. Benedicte Pasquer - Project Officer
Monday - Friday 9am -3pm
IMOS e-Marine Information Infrastructure
University of Tasmania
Ph: +61 3 6226 1927













University of Tasmania Electronic Communications Policy (December, 2014).
This email is confidential, and is for the intended recipient only. Access, disclosure, copying, distribution, or reliance on any of it by anyone outside the intended recipient organisation is prohibited and may be a criminal offence. Please delete if obtained in error and email confirmation to the sender. The views expressed in this email are not necessarily the views of the University of Tasmania, unless clearly intended otherwise.

**Comment by dnahodil** [comment]
:chocolate_bar: vs :beer:

**Comment by danfruehauf** [comment]
More like:
:chocolate_bar: vs :beer: :beer: :beer: :beer: :beer: :beer:

**Comment by lbesnard** [comment]
my life's hard !

**Comment by danfruehauf** [comment]
Harvester removed from prod. Will be pushed again when the data collection is ready to be published.
