### ISSUE TITLE
talend srs_sst failing

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#129]
Due to a bogus file:
```
Exception in component iNetCDFGlobalAttributes_1
java.io.IOException: Cant read /mnt/opendap/2/SRS/sst/ghrsst/L3S-1dS/dn/2015/20150326111000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1d_dn_Southern-v02.0-fv01.0.nc: not a valid CDM file.
        at ucar.nc2.NetcdfFile.open(NetcdfFile.java:744)
        at ucar.nc2.NetcdfFile.open(NetcdfFile.java:394)
        at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:687)
        at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:424)
        at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:407)
        at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:392)
        at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:379)
        at srs_sst.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.iNetCDFGlobalAttributes_1Process(HarvestTimeseriesFile.java:1305)
        at srs_sst.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.tPostgresqlRow_1Process(HarvestTimeseriesFile.java:808)
        at srs_sst.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.tPostgresqlConnection_1Process(HarvestTimeseriesFile.java:679)
        at srs_sst.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.iIncludeSdiLibraries_1Process(HarvestTimeseriesFile.java:556)
        at srs_sst.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.runJobInTOS(HarvestTimeseriesFile.java:3691)
        at srs_sst.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.runJob(HarvestTimeseriesFile.java:3540)
        at srs_sst.srs_sst_harvester_1_0.SRS_SST_harvester.iNewResources_1Process(SRS_SST_harvester.java:1863)
        at srs_sst.srs_sst_harvester_1_0.SRS_SST_harvester.iDeletedResources_1Process(SRS_SST_harvester.java:1646)
        at srs_sst.srs_sst_harvester_1_0.SRS_SST_harvester.iPostgresqlDbUpdate_1Process(SRS_SST_harvester.java:1314)
        at srs_sst.srs_sst_harvester_1_0.SRS_SST_harvester.iIndexFiles_1_iFilesProcess(SRS_SST_harvester.java:2616)
        at srs_sst.srs_sst_harvester_1_0.SRS_SST_harvester.runJobInTOS(SRS_SST_harvester.java:4336)
        at srs_sst.srs_sst_harvester_1_0.SRS_SST_harvester.main(SRS_SST_harvester.java:4168)
Exception while processing /mnt/opendap/2/SRS/sst/ghrsst/L3S-1dS/dn/2015/20150326111000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1d_dn_Southern-v02.0-fv01.0.nc
java.lang.RuntimeException: Child job running failed
        at srs_sst.srs_sst_harvester_1_0.SRS_SST_harvester.iNewResources_1Process(SRS_SST_harvester.java:1874)
        at srs_sst.srs_sst_harvester_1_0.SRS_SST_harvester.iDeletedResources_1Process(SRS_SST_harvester.java:1646)
        at srs_sst.srs_sst_harvester_1_0.SRS_SST_harvester.iPostgresqlDbUpdate_1Process(SRS_SST_harvester.java:1314)
        at srs_sst.srs_sst_harvester_1_0.SRS_SST_harvester.iIndexFiles_1_iFilesProcess(SRS_SST_harvester.java:2616)
        at srs_sst.srs_sst_harvester_1_0.SRS_SST_harvester.runJobInTOS(SRS_SST_harvester.java:4336)
        at srs_sst.srs_sst_harvester_1_0.SRS_SST_harvester.main(SRS_SST_harvester.java:4168)
```

**Comment by smancini** [comment]
Edward King Has fixed the issue with this particular file. The harvester seems to be running fine now.
