### ISSUE TITLE
talend aodn_mhl_sst failing

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#132]
Not entirely sure what's that error, but here it is:
```
Exception in component iUpdateSpatialExtent_1
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
        at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
        at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
        at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
        at org.postgresql.jdbc3g.Jdbc3gConnection.<init>(Jdbc3gConnection.java:24)
        at org.postgresql.Driver.makeConnection(Driver.java:393)
        at org.postgresql.Driver.connect(Driver.java:267)
        at java.sql.DriverManager.getConnection(DriverManager.java:571)
        at java.sql.DriverManager.getConnection(DriverManager.java:215)
        at aodn_mhl_sst.updatemetadata_0_1.UpdateMetadata.iUpdateSpatialExtent_1Process(UpdateMetadata.java:446)
        at aodn_mhl_sst.updatemetadata_0_1.UpdateMetadata.runJobInTOS(UpdateMetadata.java:846)
        at aodn_mhl_sst.updatemetadata_0_1.UpdateMetadata.runJob(UpdateMetadata.java:693)
        at aodn_mhl_sst.aodn_mhl_sst_harvester_0_1.AODN_MHL_SST_harvester.tRunJob_4Process(AODN_MHL_SST_harvester.java:1472)
        at aodn_mhl_sst.aodn_mhl_sst_harvester_0_1.AODN_MHL_SST_harvester.tRunJob_3Process(AODN_MHL_SST_harvester.java:1357)
        at aodn_mhl_sst.aodn_mhl_sst_harvester_0_1.AODN_MHL_SST_harvester.tRunJob_2Process(AODN_MHL_SST_harvester.java:1189)
        at aodn_mhl_sst.aodn_mhl_sst_harvester_0_1.AODN_MHL_SST_harvester.runJobInTOS(AODN_MHL_SST_harvester.java:3262)
        at aodn_mhl_sst.aodn_mhl_sst_harvester_0_1.AODN_MHL_SST_harvester.main(AODN_MHL_SST_harvester.java:3070)
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at java.net.Socket.connect(Socket.java:528)
        at org.postgresql.core.PGStream.<init>(PGStream.java:60)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
        ... 17 more
Exception in component tRunJob_4
java.lang.RuntimeException: Child job running failed
        at aodn_mhl_sst.aodn_mhl_sst_harvester_0_1.AODN_MHL_SST_harvester.tRunJob_4Process(AODN_MHL_SST_harvester.java:1483)
        at aodn_mhl_sst.aodn_mhl_sst_harvester_0_1.AODN_MHL_SST_harvester.tRunJob_3Process(AODN_MHL_SST_harvester.java:1357)
        at aodn_mhl_sst.aodn_mhl_sst_harvester_0_1.AODN_MHL_SST_harvester.tRunJob_2Process(AODN_MHL_SST_harvester.java:1189)
        at aodn_mhl_sst.aodn_mhl_sst_harvester_0_1.AODN_MHL_SST_harvester.runJobInTOS(AODN_MHL_SST_harvester.java:3262)
        at aodn_mhl_sst.aodn_mhl_sst_harvester_0_1.AODN_MHL_SST_harvester.main(AODN_MHL_SST_harvester.java:3070)
```

**Comment by bpasquer** [comment]
I was waiting for @lbesnard  to come back to help me sorting this problem

**Comment by danfruehauf** [comment]
Closed by https://github.com/aodn/harvesters/pull/282
