### ISSUE TITLE
talend aodn_ran_ctd failing

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#133]
Error below:
```
Exception in component iUpdateSpatialExtent_1
org.postgresql.util.PSQLException: ERROR: relation "aodn_ran_ctd.aodn_ran_ctd" does not exist
  Where: PL/pgSQL function boundingpolygon(text,text,text,double precision) line 9 at EXECUTE statement
PL/pgSQL function boundingpolygonasgml3(text,text,text,double precision) line 6 at assignment
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2157)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1886)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:555)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:403)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:283)
        at aodn_ran_ctd.updatemetadata_0_1.UpdateMetadata.iUpdateSpatialExtent_1Process(UpdateMetadata.java:469)
        at aodn_ran_ctd.updatemetadata_0_1.UpdateMetadata.runJobInTOS(UpdateMetadata.java:806)
        at aodn_ran_ctd.updatemetadata_0_1.UpdateMetadata.runJob(UpdateMetadata.java:653)
        at aodn_ran_ctd.ran_ctd_harvester_0_1.RAN_CTD_harvester.tRunJob_4Process(RAN_CTD_harvester.java:1472)
        at aodn_ran_ctd.ran_ctd_harvester_0_1.RAN_CTD_harvester.tRunJob_3Process(RAN_CTD_harvester.java:1357)
        at aodn_ran_ctd.ran_ctd_harvester_0_1.RAN_CTD_harvester.tRunJob_2Process(RAN_CTD_harvester.java:1189)
        at aodn_ran_ctd.ran_ctd_harvester_0_1.RAN_CTD_harvester.runJobInTOS(RAN_CTD_harvester.java:3262)
        at aodn_ran_ctd.ran_ctd_harvester_0_1.RAN_CTD_harvester.main(RAN_CTD_harvester.java:3070)
Exception in component tRunJob_4
java.lang.RuntimeException: Child job running failed
        at aodn_ran_ctd.ran_ctd_harvester_0_1.RAN_CTD_harvester.tRunJob_4Process(RAN_CTD_harvester.java:1483)
        at aodn_ran_ctd.ran_ctd_harvester_0_1.RAN_CTD_harvester.tRunJob_3Process(RAN_CTD_harvester.java:1357)
        at aodn_ran_ctd.ran_ctd_harvester_0_1.RAN_CTD_harvester.tRunJob_2Process(RAN_CTD_harvester.java:1189)
        at aodn_ran_ctd.ran_ctd_harvester_0_1.RAN_CTD_harvester.runJobInTOS(RAN_CTD_harvester.java:3262)
        at aodn_ran_ctd.ran_ctd_harvester_0_1.RAN_CTD_harvester.main(RAN_CTD_harvester.java:3070)
```

If it need a complete schema drop, we can do that.

**Comment by danfruehauf** [comment]
On RC the harvester now runs successfully.

On prod, the harvester is still running, but the metadata record is not published. I'll give @bpasquer a week of grace before I (again) remove that harvester from running in prod.

**Comment by danfruehauf** [comment]
Record is published, all good.
