### ISSUE TITLE
talend aus_phyto_db failing

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#142]
Missing a metadata record in production.

```
Exception in component iUpdateSpatialExtent_1
it.geosolutions.geonetwork.exception.GNServerException: Error retrieving metadata in GeoNetwork
        at it.geosolutions.geonetwork.op.GNMetadataGet.gnGetMetadata(GNMetadataGet.java:82)
        at it.geosolutions.geonetwork.op.GNMetadataGet.get(GNMetadataGet.java:63)
        at it.geosolutions.geonetwork.op.GNMetadataGet.get(GNMetadataGet.java:58)
        at it.geosolutions.geonetwork.GNClient.get(GNClient.java:122)
        at aus_phyto_db.metadata_update_0_1.metadata_update.iUpdateSpatialExtent_1Process(metadata_update.java:791)
        at aus_phyto_db.metadata_update_0_1.metadata_update.tPostgresqlClose_1Process(metadata_update.java:595)
        at aus_phyto_db.metadata_update_0_1.metadata_update.tPostjob_1Process(metadata_update.java:492)
        at aus_phyto_db.metadata_update_0_1.metadata_update.runJobInTOS(metadata_update.java:1091)
        at aus_phyto_db.metadata_update_0_1.metadata_update.runJob(metadata_update.java:919)
        at aus_phyto_db.aus_phyto_db_harvester_0_1.AUS_PHYTO_DB_harvester.tRunJob_3Process(AUS_PHYTO_DB_harvester.java:2111)
        at aus_phyto_db.aus_phyto_db_harvester_0_1.AUS_PHYTO_DB_harvester.tPostgresqlClose_1Process(AUS_PHYTO_DB_harvester.java:1663)
        at aus_phyto_db.aus_phyto_db_harvester_0_1.AUS_PHYTO_DB_harvester.iPostgresqlDbUpdate_1Process(AUS_PHYTO_DB_harvester.java:1558)
        at aus_phyto_db.aus_phyto_db_harvester_0_1.AUS_PHYTO_DB_harvester.tPostgresqlConnection_1Process(AUS_PHYTO_DB_harvester.java:1293)
        at aus_phyto_db.aus_phyto_db_harvester_0_1.AUS_PHYTO_DB_harvester.iIncludeSdiLibraries_1Process(AUS_PHYTO_DB_harvester.java:1159)
        at aus_phyto_db.aus_phyto_db_harvester_0_1.AUS_PHYTO_DB_harvester.runJobInTOS(AUS_PHYTO_DB_harvester.java:3901)
        at aus_phyto_db.aus_phyto_db_harvester_0_1.AUS_PHYTO_DB_harvester.main(AUS_PHYTO_DB_harvester.java:3709)
Exception in component tRunJob_3
java.lang.RuntimeException: Child job running failed
        at aus_phyto_db.aus_phyto_db_harvester_0_1.AUS_PHYTO_DB_harvester.tRunJob_3Process(AUS_PHYTO_DB_harvester.java:2122)
        at aus_phyto_db.aus_phyto_db_harvester_0_1.AUS_PHYTO_DB_harvester.tPostgresqlClose_1Process(AUS_PHYTO_DB_harvester.java:1663)
        at aus_phyto_db.aus_phyto_db_harvester_0_1.AUS_PHYTO_DB_harvester.iPostgresqlDbUpdate_1Process(AUS_PHYTO_DB_harvester.java:1558)
        at aus_phyto_db.aus_phyto_db_harvester_0_1.AUS_PHYTO_DB_harvester.tPostgresqlConnection_1Process(AUS_PHYTO_DB_harvester.java:1293)
        at aus_phyto_db.aus_phyto_db_harvester_0_1.AUS_PHYTO_DB_harvester.iIncludeSdiLibraries_1Process(AUS_PHYTO_DB_harvester.java:1159)
        at aus_phyto_db.aus_phyto_db_harvester_0_1.AUS_PHYTO_DB_harvester.runJobInTOS(AUS_PHYTO_DB_harvester.java:3901)
        at aus_phyto_db.aus_phyto_db_harvester_0_1.AUS_PHYTO_DB_harvester.main(AUS_PHYTO_DB_harvester.java:3709)
finish;2015-10-07 21:23:10+11:00 9 minutes
```

**Comment by danfruehauf** [comment]
Been almost a month. This harvester will be removed from production until it has a metadata record.

**Comment by danfruehauf** [comment]
Times up for this one. Removed from prod.

**Comment by danfruehauf** [comment]
Actually, keep that open:
```
Exception in component tFileInputDelimited_1
java.lang.Exception: Column(s) missing
        at aus_phyto_db.metadata_harvest_0_1.metadata_harvest$1RowHelper_tFileInputDelimited_1.valueToConn(metadata_harvest.java:1988)
        at aus_phyto_db.metadata_harvest_0_1.metadata_harvest.tFileInputDelimited_1Process(metadata_harvest.java:2138)
        at aus_phyto_db.metadata_harvest_0_1.metadata_harvest.tFileFetch_1Process(metadata_harvest.java:890)
        at aus_phyto_db.metadata_harvest_0_1.metadata_harvest.tPostgresqlConnection_1Process(metadata_harvest.java:649)
        at aus_phyto_db.metadata_harvest_0_1.metadata_harvest.iIncludeSdiLibraries_1Process(metadata_harvest.java:531)
        at aus_phyto_db.metadata_harvest_0_1.metadata_harvest.runJobInTOS(metadata_harvest.java:4600)
        at aus_phyto_db.metadata_harvest_0_1.metadata_harvest.runJob(metadata_harvest.java:4457)
        at aus_phyto_db.aus_phyto_db_harvester_0_1.AUS_PHYTO_DB_harvester.tRunJob_2Process(AUS_PHYTO_DB_harvester.java:1814)
        at aus_phyto_db.aus_phyto_db_harvester_0_1.AUS_PHYTO_DB_harvester.tPostgresqlClose_1Process(AUS_PHYTO_DB_harvester.java:1686)
        at aus_phyto_db.aus_phyto_db_harvester_0_1.AUS_PHYTO_DB_harvester.iPostgresqlDbUpdate_1Process(AUS_PHYTO_DB_harvester.java:1583)
        at aus_phyto_db.aus_phyto_db_harvester_0_1.AUS_PHYTO_DB_harvester.tPostgresqlConnection_1Process(AUS_PHYTO_DB_harvester.java:1293)
        at aus_phyto_db.aus_phyto_db_harvester_0_1.AUS_PHYTO_DB_harvester.iIncludeSdiLibraries_1Process(AUS_PHYTO_DB_harvester.java:1159)
        at aus_phyto_db.aus_phyto_db_harvester_0_1.AUS_PHYTO_DB_harvester.runJobInTOS(AUS_PHYTO_DB_harvester.java:3926)
        at aus_phyto_db.aus_phyto_db_harvester_0_1.AUS_PHYTO_DB_harvester.main(AUS_PHYTO_DB_harvester.java:3734)
Exception in component tRunJob_2
java.lang.RuntimeException: Child job running failed
        at aus_phyto_db.aus_phyto_db_harvester_0_1.AUS_PHYTO_DB_harvester.tRunJob_2Process(AUS_PHYTO_DB_harvester.java:1825)
        at aus_phyto_db.aus_phyto_db_harvester_0_1.AUS_PHYTO_DB_harvester.tPostgresqlClose_1Process(AUS_PHYTO_DB_harvester.java:1686)
        at aus_phyto_db.aus_phyto_db_harvester_0_1.AUS_PHYTO_DB_harvester.iPostgresqlDbUpdate_1Process(AUS_PHYTO_DB_harvester.java:1583)
        at aus_phyto_db.aus_phyto_db_harvester_0_1.AUS_PHYTO_DB_harvester.tPostgresqlConnection_1Process(AUS_PHYTO_DB_harvester.java:1293)
        at aus_phyto_db.aus_phyto_db_harvester_0_1.AUS_PHYTO_DB_harvester.iIncludeSdiLibraries_1Process(AUS_PHYTO_DB_harvester.java:1159)
        at aus_phyto_db.aus_phyto_db_harvester_0_1.AUS_PHYTO_DB_harvester.runJobInTOS(AUS_PHYTO_DB_harvester.java:3926)
        at aus_phyto_db.aus_phyto_db_harvester_0_1.AUS_PHYTO_DB_harvester.main(AUS_PHYTO_DB_harvester.java:3734)
```

**Comment by danfruehauf** [comment]
Friendly reminder - no action was taken on this harvester and it is not actively monitored any more.

**Comment by danfruehauf** [comment]
What's up with that? Anyone?

**Comment by mhidas** [comment]
I haven't had much to do with this, but I thought this was just a one-off harvest to create a static copy of this db for publication attached to a DOI.

@atkinsn or @lbesnard  might know more?

**Comment by lbesnard** [comment]
nothing for the next few months. The person who has created the data changed the geoserver layer content, and is now  on a ship or something.
