### ISSUE TITLE
talend anmn_nrs_rt_biogeochem_timeseries, anmn_nrs_rt_biogeochem_timeseries failing

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#150]
I believe they are failing because of the same reason (and file):
```
Contents of BatchUpdateException:
SQL exception:
 Message: Batch entry 0 INSERT INTO "anmn_nrs_rt_meteo"."timeseries" ("file_id","site_code","platform_code","deployment_code","instrument_nominal_depth","site_nominal_depth","instrument","time_coverage_start","time_coverage_end") VALUES (312,'NRSNSI','NRSMAI-Surface','NRSNSI-Surface-13-2015-09',-2.0,61.8,'Vaisala WXT520','2015-09-02 10:40:03.000000 +10:00:00','2015-11-12 10:11:01.000000 +11:00:00') was aborted.  Call getNextException to see the cause.
 SQLSTATE: 23505
 Error code: 0
 Stacktrace:java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "anmn_nrs_rt_meteo"."timeseries" ("file_id","site_code","platform_code","deployment_code","instrument_nominal_depth","site_nominal_depth","instrument","time_coverage_start","time_coverage_end") VALUES (312,'NRSNSI','NRSMAI-Surface','NRSNSI-Surface-13-2015-09',-2.0,61.8,'Vaisala WXT520','2015-09-02 10:40:03.000000 +10:00:00','2015-11-12 10:11:01.000000 +11:00:00') was aborted.  Call getNextException to see the cause.
        at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2746)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1887)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2893)
        at anmn_nrs_rt_meteo_timeseries.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.iNetCDFGlobalAttributes_1Process(HarvestTimeseriesFile.java:1924)
        at anmn_nrs_rt_meteo_timeseries.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.tPostgresqlRow_1Process(HarvestTimeseriesFile.java:878)
        at anmn_nrs_rt_meteo_timeseries.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.tPostgresqlConnection_1Process(HarvestTimeseriesFile.java:749)
        at anmn_nrs_rt_meteo_timeseries.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.iIncludeSdiLibraries_1Process(HarvestTimeseriesFile.java:626)
        at anmn_nrs_rt_meteo_timeseries.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.runJobInTOS(HarvestTimeseriesFile.java:8774)
        at anmn_nrs_rt_meteo_timeseries.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.runJob(HarvestTimeseriesFile.java:8627)
        at anmn_nrs_rt_meteo_timeseries.anmn_nrs_rt_meteo_timeseries_harvester_1_0.ANMN_NRS_RT_Meteo_timeseries_harvester.iHarvestResources_1Process(ANMN_NRS_RT_Meteo_timeseries_harvester.java:2026)
        at anmn_nrs_rt_meteo_timeseries.anmn_nrs_rt_meteo_timeseries_harvester_1_0.ANMN_NRS_RT_Meteo_timeseries_harvester.iDeletedResources_1Process(ANMN_NRS_RT_Meteo_timeseries_harvester.java:1801)
        at anmn_nrs_rt_meteo_timeseries.anmn_nrs_rt_meteo_timeseries_harvester_1_0.ANMN_NRS_RT_Meteo_timeseries_harvester.iPostgresqlDbUpdate_1Process(ANMN_NRS_RT_Meteo_timeseries_harvester.java:1462)
        at anmn_nrs_rt_meteo_timeseries.anmn_nrs_rt_meteo_timeseries_harvester_1_0.ANMN_NRS_RT_Meteo_timeseries_harvester.iIndexFiles_1_iFilesProcess(ANMN_NRS_RT_Meteo_timeseries_harvester.java:3072)
        at anmn_nrs_rt_meteo_timeseries.anmn_nrs_rt_meteo_timeseries_harvester_1_0.ANMN_NRS_RT_Meteo_timeseries_harvester.runJobInTOS(ANMN_NRS_RT_Meteo_timeseries_harvester.java:4820)
        at anmn_nrs_rt_meteo_timeseries.anmn_nrs_rt_meteo_timeseries_harvester_1_0.ANMN_NRS_RT_Meteo_timeseries_harvester.main(ANMN_NRS_RT_Meteo_timeseries_harvester.java:4624)

SQL exception:
 Message: ERROR: duplicate key value violates unique constraint "timeseries_platform_start_unique"
  Detail: Key (platform_code, time_coverage_start)=(NRSMAI-Surface, 2015-09-02 10:40:03+10) already exists.
 SQLSTATE: 23505
```

**Comment by mhidas** [comment]
We ended up with duplicate files because they changed the deployment codes. I deleted the old ones (on /mnt/imos-t3) and these harvesters ran fine.

@danfruehauf For the moment I don't have a way to delete these duplicates on S3. The `po_s3_del` command fails with:`/bin/bash: /tmp/tmp.LE5Y90nh9Q: Permission denied`)

**Comment by danfruehauf** [comment]
@mhidas Ouch. I'll have a look at those. What files do you need to delete?

**Comment by mhidas** [comment]
Files to be deleted on S3:
```
IMOS/ANMN/NRS/REAL_TIME/NRSNSI/Biogeochem_timeseries/IMOS_ANMN-NRS_TPSOBUE_20150902T004438Z_NRSNSI_FV00_NRSNSI-SubSurface-2015-09-02-WQM-20-realtime.nc
IMOS/ANMN/NRS/REAL_TIME/NRSNSI/Biogeochem_timeseries/IMOS_ANMN-NRS_TPSOBUE_20150902T004442Z_NRSNSI_FV00_NRSNSI-SubSurface-2015-09-02-WQM-60-realtime.nc
IMOS/ANMN/NRS/REAL_TIME/NRSNSI/Meteorology/IMOS_ANMN-NRS_MT_20150902T004003Z_NRSNSI_FV00_NRSNSI-Surface-2015-09-02-MET-realtime.nc
```

**Comment by danfruehauf** [comment]
@mhidas Done, deleted those on S3. Thanks for following up on those.

I still need to implement the delete command on S3, I did not forget it.

**Comment by danfruehauf** [comment]
@mhidas See also https://github.com/aodn/data-services/pull/252
