### ISSUE TITLE
anmn_delayed harvester failing with 'syntax error' on one file

### ISSUE THREAD

**Issue by mhidas** [aodn/content#152]
Seems to harvest everything else ok, so I'm assuming the problem is in this one file, or the way it is presented by OPENDAP. The harvester log says:
```
yyerror: line 261 near |Data|; syntax error, unexpected SCAN_WORD, expecting ';' or ','
Illegal attribute
opendap.dap.parsers.ParseException: context: ^
        at opendap.dap.parsers.Dapparse.dap_parse_error(Dapparse.java:500)
        at opendap.dap.parsers.Dapparse.daperror(Dapparse.java:487)
        at opendap.dap.parsers.DapParser.yyaction(DapParser.java:745)
        at opendap.dap.parsers.DapParser.parse(DapParser.java:1425)
        at opendap.dap.parsers.DapParser.parse(DapParser.java:1978)
        at opendap.dap.parsers.Dapparse.dapparse(Dapparse.java:115)
        at opendap.dap.parsers.Dapparse.dasparse(Dapparse.java:131)
        at opendap.dap.DAS.parse(DAS.java:137)
        at opendap.dap.DConnect2$DASCommand.process(DConnect2.java:468)
        at opendap.dap.DConnect2.openConnection(DConnect2.java:308)
        at opendap.dap.DConnect2.getDAS(DConnect2.java:455)
        at netcdfharvester.globalattributeharvester_0_1.GlobalAttributeHarvester.iOPeNDAPAttribute_1Process(GlobalAttributeHarvester.java:1819)
        at netcdfharvester.globalattributeharvester_0_1.GlobalAttributeHarvester.tPostgresqlRow_1Process(GlobalAttributeHarvester.java:1234)
        at netcdfharvester.globalattributeharvester_0_1.GlobalAttributeHarvester.tFixedFlowInput_1Process(GlobalAttributeHarvester.java:1105)
        at netcdfharvester.globalattributeharvester_0_1.GlobalAttributeHarvester.tPostgresqlConnection_1Process(GlobalAttributeHarvester.java:508)
        at netcdfharvester.globalattributeharvester_0_1.GlobalAttributeHarvester.runJobInTOS(GlobalAttributeHarvester.java:2521)
        at netcdfharvester.globalattributeharvester_0_1.GlobalAttributeHarvester.runJob(GlobalAttributeHarvester.java:2363)
        at netcdfharvester.anmnharvest_0_1.AnmnHarvest.iHarvestResources_1Process(AnmnHarvest.java:1773)
        at netcdfharvester.anmnharvest_0_1.AnmnHarvest.iIndexThreddsResources_1_iThreddsProcess(AnmnHarvest.java:3301)
        at netcdfharvester.anmnharvest_0_1.AnmnHarvest.tRunJob_4Process(AnmnHarvest.java:1547)
        at netcdfharvester.anmnharvest_0_1.AnmnHarvest.iPostgresqlDbUpdate_1Process(AnmnHarvest.java:1379)
        at netcdfharvester.anmnharvest_0_1.AnmnHarvest.runJobInTOS(AnmnHarvest.java:5045)
        at netcdfharvester.anmnharvest_0_1.AnmnHarvest.main(AnmnHarvest.java:4853)
Exception in component iOPeNDAPAttribute_1
java.lang.NullPointerException
        at netcdfharvester.globalattributeharvester_0_1.GlobalAttributeHarvester.iOPeNDAPAttribute_1Process(GlobalAttributeHarvester.java:1821)
        at netcdfharvester.globalattributeharvester_0_1.GlobalAttributeHarvester.tPostgresqlRow_1Process(GlobalAttributeHarvester.java:1234)
        at netcdfharvester.globalattributeharvester_0_1.GlobalAttributeHarvester.tFixedFlowInput_1Process(GlobalAttributeHarvester.java:1105)
        at netcdfharvester.globalattributeharvester_0_1.GlobalAttributeHarvester.tPostgresqlConnection_1Process(GlobalAttributeHarvester.java:508)
        at netcdfharvester.globalattributeharvester_0_1.GlobalAttributeHarvester.runJobInTOS(GlobalAttributeHarvester.java:2521)
        at netcdfharvester.globalattributeharvester_0_1.GlobalAttributeHarvester.runJob(GlobalAttributeHarvester.java:2363)
        at netcdfharvester.anmnharvest_0_1.AnmnHarvest.iHarvestResources_1Process(AnmnHarvest.java:1773)
        at netcdfharvester.anmnharvest_0_1.AnmnHarvest.iIndexThreddsResources_1_iThreddsProcess(AnmnHarvest.java:3301)
        at netcdfharvester.anmnharvest_0_1.AnmnHarvest.tRunJob_4Process(AnmnHarvest.java:1547)
        at netcdfharvester.anmnharvest_0_1.AnmnHarvest.iPostgresqlDbUpdate_1Process(AnmnHarvest.java:1379)
        at netcdfharvester.anmnharvest_0_1.AnmnHarvest.runJobInTOS(AnmnHarvest.java:5045)
        at netcdfharvester.anmnharvest_0_1.AnmnHarvest.main(AnmnHarvest.java:4853)
Exception while processing https://thredds.aodn.org.au/thredds/dodsC/IMOS/ANMN/AM/NRSKAI/CO2/delayed/IMOS_ANMN-AM_GST_20141103T120000Z_NRSKAI_FV01_NRSKAI-CO2-1411-delayed_END_20150601T220000Z_C-20151117T112231Z.nc
java.lang.RuntimeException: Child job running failed
        at netcdfharvester.anmnharvest_0_1.AnmnHarvest.iHarvestResources_1Process(AnmnHarvest.java:1784)
        at netcdfharvester.anmnharvest_0_1.AnmnHarvest.iIndexThreddsResources_1_iThreddsProcess(AnmnHarvest.java:3301)
        at netcdfharvester.anmnharvest_0_1.AnmnHarvest.tRunJob_4Process(AnmnHarvest.java:1547)
        at netcdfharvester.anmnharvest_0_1.AnmnHarvest.iPostgresqlDbUpdate_1Process(AnmnHarvest.java:1379)
        at netcdfharvester.anmnharvest_0_1.AnmnHarvest.runJobInTOS(AnmnHarvest.java:5045)
        at netcdfharvester.anmnharvest_0_1.AnmnHarvest.main(AnmnHarvest.java:4853)
```

I don't see anything obviously wrong with the file, and I can see it ok on OPENDAP.

@jonescc Any ideas how we can debug this one?

**Comment by mhidas** [comment]
Ps... This harvester is pretty old and only used for reporting, as are with *anmn_realtime* and *abos*. They're not even in the harvesters repo. I'm proposing to replace these with a single new harvester, which looks at the filesystem, initially, and is made event-driven when we migrate all the data to S3.

**Comment by danfruehauf** [comment]
3 more days and then this harvester will stop being monitored.

**Comment by danfruehauf** [comment]
Friendly reminder - no action was taken on this harvester and it is not actively monitored any more.

**Comment by danfruehauf** [comment]
Migrated to pipeline. Harvester is monitored again.
