### ISSUE TITLE
talend srs_sst failing (bad file)

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#153]
```
Exception in component iNetCDFGlobalAttributes_1
java.io.IOException: Stream Closed
        at java.io.RandomAccessFile.length(Native Method)
        at ucar.unidata.io.RandomAccessFile.close(RandomAccessFile.java:343)
        at ucar.nc2.NetcdfFile.open(NetcdfFile.java:396)
        at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:687)
        at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:424)
        at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:407)
        at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:392)
        at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:379)
        at srs_sst.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.iNetCDFGlobalAttributes_1Process(HarvestTimeseriesFile.java:1305)
        at srs_sst.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.tPostgresqlRow_1Process(HarvestTimeseriesFile.java:808)
        at srs_sst.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.tPostgresqlConnection_1Process(HarvestTimeseriesFile.java:679)
        at srs_sst.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.iIncludeSdiLibraries_1Process(HarvestTimeseriesFile.java:556)
        at srs_sst.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.runJobInTOS(HarvestTimeseriesFile.java:3691)
        at srs_sst.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.runJob(HarvestTimeseriesFile.java:3540)
        at srs_sst.srs_sst_harvester_1_0.SRS_SST_harvester.iNewResources_1Process(SRS_SST_harvester.java:1863)
        at srs_sst.srs_sst_harvester_1_0.SRS_SST_harvester.iDeletedResources_1Process(SRS_SST_harvester.java:1646)
        at srs_sst.srs_sst_harvester_1_0.SRS_SST_harvester.iPostgresqlDbUpdate_1Process(SRS_SST_harvester.java:1314)
        at srs_sst.srs_sst_harvester_1_0.SRS_SST_harvester.iIndexFiles_1_iFilesProcess(SRS_SST_harvester.java:2616)
        at srs_sst.srs_sst_harvester_1_0.SRS_SST_harvester.runJobInTOS(SRS_SST_harvester.java:4336)
        at srs_sst.srs_sst_harvester_1_0.SRS_SST_harvester.main(SRS_SST_harvester.java:4168)
Exception while processing /mnt/opendap/2/SRS/sst/ghrsst/L3U-S/n15/2001/20011221081904-ABOM-L3U_GHRSST-SSTskin-AVHRR15_D-Asc_Southern-v02.0-fv02.0.nc
java.lang.RuntimeException: Child job running failed
        at srs_sst.srs_sst_harvester_1_0.SRS_SST_harvester.iNewResources_1Process(SRS_SST_harvester.java:1874)
        at srs_sst.srs_sst_harvester_1_0.SRS_SST_harvester.iDeletedResources_1Process(SRS_SST_harvester.java:1646)
        at srs_sst.srs_sst_harvester_1_0.SRS_SST_harvester.iPostgresqlDbUpdate_1Process(SRS_SST_harvester.java:1314)
        at srs_sst.srs_sst_harvester_1_0.SRS_SST_harvester.iIndexFiles_1_iFilesProcess(SRS_SST_harvester.java:2616)
        at srs_sst.srs_sst_harvester_1_0.SRS_SST_harvester.runJobInTOS(SRS_SST_harvester.java:4336)
        at srs_sst.srs_sst_harvester_1_0.SRS_SST_harvester.main(SRS_SST_harvester.java:4168)
```

**Comment by danfruehauf** [comment]
More info, some repeating lines like:
```
Dec 07, 2015 2:58:54 AM ucar.nc2.iosp.hdf5.H5header$MessageAttribute read
SEVERE: bad version 72 at filePos 79730492
```

**Comment by lbesnard** [comment]
this kind of error has always been weird, I remember showing this to @jonescc . The file is still being harvester properly tho.

Different errors today , related maybe to this file not being accessible through thredds but ok through FS
http://thredds.aodn.org.au/thredds/catalog/srs/sst/ghrsst/L3U-S/n16/2010/catalog.html?dataset=srs/sst/ghrsst/L3U-S/n16/2010/20100730114202-ABOM-L3U_GHRSST-SSTskin-AVHRR16_D-Asc_Southern-v02.0-fv02.0.nc

**Comment by danfruehauf** [comment]
Would be good to get this sorted out...

**Comment by danfruehauf** [comment]
Somewhere along the way, this was solved. New files coming in daily and we have no control of what comes in and when.
