### ISSUE TITLE
SOOP_TRV error files

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#160]
Files are:
```
IMOS_SOOP-TRV_S_20151130T140000Z_VMQ9273_FV01_END-20151219T030738Z_C-20151220T191344Z.nc
IMOS_SOOP-TRV_T_20151130T140000Z_VMQ9273_FV01_END-20151219T030738Z_C-20151220T192200Z.nc
```

Error is:
```
Dec 20, 2015 10:04:18 PM org.geotools.referencing.factory.DeferredAuthorityFactory disposeBackingStore
INFO: Disposing class org.geotools.referencing.factory.epsg.ThreadedHsqlEpsgFactory backing store
Exception in component tPostgresqlRow_2
org.postgresql.util.PSQLException: ERROR: array size exceeds the maximum allowed (1073741823)
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2157)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1886)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:555)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:403)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:395)
        at soop_trv.onefileprocess_0_1.oneFileProcess.tPostgresqlRow_3Process(oneFileProcess.java:11705)
        at soop_trv.onefileprocess_0_1.oneFileProcess.tPostgresqlCommit_5Process(oneFileProcess.java:11455)
        at soop_trv.onefileprocess_0_1.oneFileProcess.tPostgresqlRow_1Process(oneFileProcess.java:11347)
        at soop_trv.onefileprocess_0_1.oneFileProcess.tPostgresqlCommit_6Process(oneFileProcess.java:10874)
        at soop_trv.onefileprocess_0_1.oneFileProcess.iNetCDFInput_1Process(oneFileProcess.java:10763)
        at soop_trv.onefileprocess_0_1.oneFileProcess.iNetCDFGlobalAttributes_1Process(oneFileProcess.java:5079)
        at soop_trv.onefileprocess_0_1.oneFileProcess.tPostgresqlInput_3Process(oneFileProcess.java:1302)
        at soop_trv.onefileprocess_0_1.oneFileProcess.tPostgresqlConnection_1Process(oneFileProcess.java:952)
        at soop_trv.onefileprocess_0_1.oneFileProcess.iIncludeSdiLibraries_1Process(oneFileProcess.java:834)
        at soop_trv.onefileprocess_0_1.oneFileProcess.runJobInTOS(oneFileProcess.java:14833)
        at soop_trv.onefileprocess_0_1.oneFileProcess.runJob(oneFileProcess.java:14680)
        at soop_trv.soop_trv_harvester_0_1.SOOP_TRV_harvester.iNewOrModifiedFileList_1Process(SOOP_TRV_harvester.java:2146)
        at soop_trv.soop_trv_harvester_0_1.SOOP_TRV_harvester.iPostgresqlDbUpdate_1Process(SOOP_TRV_harvester.java:1924)
        at soop_trv.soop_trv_harvester_0_1.SOOP_TRV_harvester.iUpdateIndex_1Process(SOOP_TRV_harvester.java:1308)
        at soop_trv.soop_trv_harvester_0_1.SOOP_TRV_harvester.iPostgresqlDbUpdate_2Process(SOOP_TRV_harvester.java:1194)
        at soop_trv.soop_trv_harvester_0_1.SOOP_TRV_harvester.runJobInTOS(SOOP_TRV_harvester.java:4594)
        at soop_trv.soop_trv_harvester_0_1.SOOP_TRV_harvester.main(SOOP_TRV_harvester.java:4430)
Exception in component tRunJob_2
java.lang.RuntimeException: Child job running failed
        at soop_trv.soop_trv_harvester_0_1.SOOP_TRV_harvester.iNewOrModifiedFileList_1Process(SOOP_TRV_harvester.java:2157)
        at soop_trv.soop_trv_harvester_0_1.SOOP_TRV_harvester.iPostgresqlDbUpdate_1Process(SOOP_TRV_harvester.java:1924)
        at soop_trv.soop_trv_harvester_0_1.SOOP_TRV_harvester.iUpdateIndex_1Process(SOOP_TRV_harvester.java:1308)
        at soop_trv.soop_trv_harvester_0_1.SOOP_TRV_harvester.iPostgresqlDbUpdate_2Process(SOOP_TRV_harvester.java:1194)
        at soop_trv.soop_trv_harvester_0_1.SOOP_TRV_harvester.runJobInTOS(SOOP_TRV_harvester.java:4594)
        at soop_trv.soop_trv_harvester_0_1.SOOP_TRV_harvester.main(SOOP_TRV_harvester.java:4430)
2015-12-20 21:03:51;REQzC7;REQzC7;REQzC7;11675;SOOP_TRV;SOOP_TRV_harvester;_-H3_wEsvEeOpS4EfPHUwwQ;0.1;Default;;begin;;
```

**Comment by danfruehauf** [comment]
Fixed by https://github.com/aodn/harvesters/pull/344
