### ISSUE TITLE
talend abos_sots failing

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#172]
In the log:
```
begin;2016-01-13 15:40:25+11:00
INFO 13/01/16 3:40 PM:liquibase: Successfully acquired change log lock
INFO 13/01/16 3:40 PM:liquibase: Reading from abos_sots.databasechangelog
INFO 13/01/16 3:40 PM:liquibase: Reading from abos_sots.databasechangelog
INFO 13/01/16 3:40 PM:liquibase: Successfully released change log lock
Exception in component iUpdateIndex_1
java.lang.NullPointerException
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:101)
        at java.io.FileReader.<init>(FileReader.java:58)
        at au.org.emii.talend.updateindex.Component.run(Component.java:29)
        at abos_sots.abos_sots_harvester_0_1.ABOS_SOTS_harvester.iUpdateIndex_1Process(ABOS_SOTS_harvester.java:1119)
        at abos_sots.abos_sots_harvester_0_1.ABOS_SOTS_harvester.runJobInTOS(ABOS_SOTS_harvester.java:3972)
        at abos_sots.abos_sots_harvester_0_1.ABOS_SOTS_harvester.main(ABOS_SOTS_harvester.java:3780)
finish;2016-01-13 15:40:34+11:00 0 minutes
```

**Comment by mhidas** [comment]
@danfruehauf My bad. I accidentally ran it manually using `talend_run`, but it has already been converted to be triggered by the pipeline. Should I just delete the offending console.log file to get rid of the Nagios alert?

**Comment by danfruehauf** [comment]
Ah, I'll deal with it.

I should probably disable talend_run for those harvesters...
