### ISSUE TITLE
talend aodn_ran_ctd, aodn_mhl_sst, anmn_mhlwave failing

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#174]
Same reason, www.metoc.gov.au is returning 502 (bad gateway):
```
Exception in component iIndexThreddsResources_2_iThredds
java.lang.Exception: Invalid catalog http://www.metoc.gov.au/thredds/catalog/RAN_CTD_DATA/catalog.xml
----Catalog Validation version 1.0.01
**Fatal:  InvCatalogFactory.readXML failed
 Exception= java.io.IOException Server returned HTTP response code: 502 for URL: http://www.metoc.gov.au/thredds/catalog/RAN_CTD_DATA/catalog.xml
 fatalMessages= 
 errMessages= 
 warnMessages= 

        at aodn_ran_ctd.harvestmetadatathredds_0_1.HarvestMetadataThredds$1.<init>(HarvestMetadataThredds.java:2301)
        at aodn_ran_ctd.harvestmetadatathredds_0_1.HarvestMetadataThredds.iIndexThreddsResources_2_iThreddsProcess(HarvestMetadataThredds.java:2257)
        at aodn_ran_ctd.harvestmetadatathredds_0_1.HarvestMetadataThredds.iPostgresqlDbUpdate_1Process(HarvestMetadataThredds.java:1211)
        at aodn_ran_ctd.harvestmetadatathredds_0_1.HarvestMetadataThredds.runJobInTOS(HarvestMetadataThredds.java:4345)
        at aodn_ran_ctd.harvestmetadatathredds_0_1.HarvestMetadataThredds.runJob(HarvestMetadataThredds.java:4177)
        at aodn_ran_ctd.ran_ctd_harvester_0_1.RAN_CTD_harvester.tRunJob_2Process(RAN_CTD_harvester.java:1137)
        at aodn_ran_ctd.ran_ctd_harvester_0_1.RAN_CTD_harvester.runJobInTOS(RAN_CTD_harvester.java:3262)
        at aodn_ran_ctd.ran_ctd_harvester_0_1.RAN_CTD_harvester.main(RAN_CTD_harvester.java:3070)
Exception in component tRunJob_2
java.lang.RuntimeException: Child job running failed
        at aodn_ran_ctd.ran_ctd_harvester_0_1.RAN_CTD_harvester.tRunJob_2Process(RAN_CTD_harvester.java:1148)
        at aodn_ran_ctd.ran_ctd_harvester_0_1.RAN_CTD_harvester.runJobInTOS(RAN_CTD_harvester.java:3262)
        at aodn_ran_ctd.ran_ctd_harvester_0_1.RAN_CTD_harvester.main(RAN_CTD_harvester.java:3070)
finish;2016-01-26 18:15:55+11:00 1 minutes
```

**Comment by smancini** [comment]
I have contacted Andrew Walsh at the Navy because their THREDDS catalogue is down.

**Comment by smancini** [comment]
RAN THREDDS catalogue is up again. Is this issue still relevant?

**Comment by danfruehauf** [comment]
@smancini Yeah, it's up again. I reran the harvesters and it can reach the server.

**Comment by danfruehauf** [comment]
Issue up again. Server returns 502:
```
 Exception= java.io.IOException Server returned HTTP response code: 502 for URL: http://www.metoc.gov.au/thredds/catalog/MHLWAVE/catalog.xml
 fatalMessages= 
 errMessages= 
 warnMessages= 

        at anmn_mhlwave.harvestmetadatathredds_0_1.HarvestMetadataThredds$1.<init>(HarvestMetadataThredds.java:1762)
        at anmn_mhlwave.harvestmetadatathredds_0_1.HarvestMetadataThredds.iIndexThreddsResources_2_iThreddsProcess(HarvestMetadataThredds.java:1718)
        at anmn_mhlwave.harvestmetadatathredds_0_1.HarvestMetadataThredds.iPostgresqlDbUpdate_1Process(HarvestMetadataThredds.java:672)
        at anmn_mhlwave.harvestmetadatathredds_0_1.HarvestMetadataThredds.runJobInTOS(HarvestMetadataThredds.java:3797)
        at anmn_mhlwave.harvestmetadatathredds_0_1.HarvestMetadataThredds.runJob(HarvestMetadataThredds.java:3638)
        at anmn_mhlwave.anmn_mhlwave_harvester_0_1.ANMN_MHLwave_harvester.tRunJob_2Process(ANMN_MHLwave_harvester.java:1333)
        at anmn_mhlwave.anmn_mhlwave_harvester_0_1.ANMN_MHLwave_harvester.tRunJob_1Process(ANMN_MHLwave_harvester.java:1216)
        at anmn_mhlwave.anmn_mhlwave_harvester_0_1.ANMN_MHLwave_harvester.runJobInTOS(ANMN_MHLwave_harvester.java:3459)
        at anmn_mhlwave.anmn_mhlwave_harvester_0_1.ANMN_MHLwave_harvester.main(ANMN_MHLwave_harvester.java:3263)
Exception in component tRunJob_2
java.lang.RuntimeException: Child job running failed
        at anmn_mhlwave.anmn_mhlwave_harvester_0_1.ANMN_MHLwave_harvester.tRunJob_2Process(ANMN_MHLwave_harvester.java:1344)
        at anmn_mhlwave.anmn_mhlwave_harvester_0_1.ANMN_MHLwave_harvester.tRunJob_1Process(ANMN_MHLwave_harvester.java:1216)
        at anmn_mhlwave.anmn_mhlwave_harvester_0_1.ANMN_MHLwave_harvester.runJobInTOS(ANMN_MHLwave_harvester.java:3459)
        at anmn_mhlwave.anmn_mhlwave_harvester_0_1.ANMN_MHLwave_harvester.main(ANMN_MHLwave_harvester.java:3263)
```

**Comment by danfruehauf** [comment]
Happens again now.

If this issue is not fixed this week, monitoring for those harvesters will be ignored.

**Comment by mhidas** [comment]
@danfruehauf I assume you've just removed these harvesters? They are no longer in `/mnt/ebs/talend/jobs/`

**Comment by danfruehauf** [comment]
> @danfruehauf I assume you've just removed these harvesters? They are no longer in /mnt/ebs/talend/jobs/

They are on 10-aws-syd (not 10-nsp-mel).

**Comment by mhidas** [comment]
> They are on 10-aws-syd (not 10-nsp-mel).
Oops... got my 10's mixed up/

@bpasquer @smancini Has anyone contacted the RAN about this yet? Is Andrew Walsh still our contact there?

**Comment by bpasquer** [comment]
Yes we contacted Andrew, he’s aware of the issue.
On 1 Mar 2016, at 11:22 AM, Marty Hidas <notifications@github.com<mailto:notifications@github.com>> wrote:


They are on 10-aws-syd (not 10-nsp-mel).
Oops... got my 10's mixed up/

@bpasquer<https://github.com/bpasquer> @smancini<https://github.com/smancini> Has anyone contacted the RAN about this yet? Is Andrew Walsh still our contact there?

—
Reply to this email directly or view it on GitHub<https://github.com/aodn/content/issues/174#issuecomment-190465901>.

Dr. Benedicte Pasquer
Project Officer, e-Marine Information Infrastructure, IMOS
Monday - Friday 9am -3pm
University of Tasmania, Private Bag 110, Hobart, Tasmania, 7001, Australia
Ph: +61 3 6226 1927















University of Tasmania Electronic Communications Policy (December, 2014).
This email is confidential, and is for the intended recipient only. Access, disclosure, copying, distribution, or reliance on any of it by anyone outside the intended recipient organisation is prohibited and may be a criminal offence. Please delete if obtained in error and email confirmation to the sender. The views expressed in this email are not necessarily the views of the University of Tasmania, unless clearly intended otherwise.

**Comment by smancini** [comment]
Seems to be working now.

**Comment by danfruehauf** [comment]
> Seems to be working now.

As long as someone from your team is going to look at that and inform CMAR of outages, I'm happy to close it. But it's likely to happen again.

**Comment by smancini** [comment]
Yes, I will look after that one and send e-mail to Andrew Walsh if necessary.

**Comment by danfruehauf** [comment]
> Yes, I will look after that one and send e-mail to Andrew Walsh if necessary.

:+1: :beers:
