### ISSUE TITLE
AATAMS SATTAG DM

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#211]
pipeline fails because of harvester issue 

see for example :
less /mnt/ebs/log/data-services/AATAMS_SATTAG_DM/tmp.JoMYrJr3Ov.20160608-120022.log

```
Exception in component iUpdateIndex_1
org.postgresql.util.PSQLException: FATAL: too many connections for role "aatams_sattag_dm"
```

@xhoenner

**Comment by lbesnard** [comment]
@jonescc what I don't understand is that this harvester seems to be written properly with correct tpostjobs to close the connection

**Comment by jonescc** [comment]
The harvester looks OK - we are using a couple of connections at the same time but should be OK if only one aatams_sattag_dm_harvester runs at a time.

Looking at the log directory it looks like more than one harvester ran at the same time?

-rw-r--r--  1 projectofficer projectofficer  2776 Jun  8 12:00 tmp.JehfLMTgdL.20160608-120038.log
-rw-r--r--  1 projectofficer projectofficer  2092 Jun  8 12:00 tmp.JoMYrJr3Ov.20160608-120022.log

The harvester has run successfully at other times. We only have a small number of connections available to the harvester.  Running two at a time may cause this issue.

Probably need to look at the pipeline processing that allowed this to happen.  I'm not familiar with this code so should be raise as a VIT or backlog item

**Comment by lbesnard** [comment]
@pblain this is probably a pipeline issue.

**Comment by pblain** [comment]
@lbesnard - this will need to be a VIT then.  I'll put it on the board.

**Comment by xhoenner** [comment]
probably the VIT you were mentioning this morning at the review @pblain. Not sure whether @julian1 worked on this since @lwgordonimos's face assigned to it on the whiteboard.

**Comment by xhoenner** [comment]
This issue is still oustanding as of July 12:

less /mnt/ebs/log/data-services/AATAMS_SATTAG_DM/tmp.0BvC1Y6VRA.20160712-000330.log

```
Exception in component iUpdateIndex_1
org.postgresql.util.PSQLException: FATAL: too many connections for role "aatams_sattag_dm"
        at org.postgresql.Driver$ConnectThread.getResult(Driver.java:341)
        at org.postgresql.Driver.connect(Driver.java:264)
        at java.sql.DriverManager.getConnection(DriverManager.java:571)
        at java.sql.DriverManager.getConnection(DriverManager.java:215)
        at au.org.emii.talend.updateindex.Component.run(Component.java:22)
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.iUpdateIndex_1Process(aatams_sattag_dm_harvester.java:1418)
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.tPostgresqlConnection_1Process(aatams_sattag_dm_harvester.java:1357)
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.runJobInTOS(aatams_sattag_dm_harvester.java:5661)
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.main(aatams_sattag_dm_harvester.java:5449)
```

**Comment by lbesnard** [comment]
@smancini I think we can close this one
@xhoenner  ?
