### ISSUE TITLE
Invalid style for anmn_nrs_long_ts_interpolated_data breaks GetCapabilities request

### ISSUE THREAD

**Issue by jonescc** [aodn/content#235]
Currently unable to request a GetCapabilities statement in geoserver-123 due to an issue with a style for this layer:

```
Caused by: javax.xml.transform.TransformerException: org.geoserver.platform.ServiceException: Error occurred trying to write out metadata for layer: anmn_nrs_long_ts_interpolated_data
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:755)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:359)
        at org.geotools.xml.transform.TransformerBase$Task.run(TransformerBase.java:300)
        at org.geotools.xml.transform.TransformerBase.transform(TransformerBase.java:133)
        at org.geotools.xml.transform.TransformerBase.transform(TransformerBase.java:112)
        at org.geoserver.wms.capabilities.Capabilities_1_3_0_Response.write(Capabilities_1_3_0_Response.java:48)
        ... 89 more
Caused by: org.geoserver.platform.ServiceException: Error occurred trying to write out metadata for layer: anmn_nrs_long_ts_interpolated_data
        at org.geoserver.wms.capabilities.Capabilities_1_3_0_Transformer$Capabilities_1_3_0_Translator.doHandleLayer(Capabilities_1_3_0_Transformer.java:884)
        at org.geoserver.wms.capabilities.Capabilities_1_3_0_Transformer$Capabilities_1_3_0_Translator.handleLayerTree(Capabilities_1_3_0_Transformer.java:837)
        at org.geoserver.wms.capabilities.Capabilities_1_3_0_Transformer$Capabilities_1_3_0_Translator.handleLayers(Capabilities_1_3_0_Transformer.java:717)
        at org.geoserver.wms.capabilities.Capabilities_1_3_0_Transformer$Capabilities_1_3_0_Translator.handleCapability(Capabilities_1_3_0_Transformer.java:465)
        at org.geoserver.wms.capabilities.Capabilities_1_3_0_Transformer$Capabilities_1_3_0_Translator.encode(Capabilities_1_3_0_Transformer.java:273)
        at org.geotools.xml.transform.TransformerBase$XMLReaderSupport.parse(TransformerBase.java:1026)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transformIdentity(TransformerImpl.java:677)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:746)
        ... 94 more
Caused by: java.lang.NullPointerException
        at org.geoserver.wms.capabilities.Capabilities_1_3_0_Transformer$Capabilities_1_3_0_Translator.handleStyles(Capabilities_1_3_0_Transformer.java:1041)
        at org.geoserver.wms.capabilities.Capabilities_1_3_0_Transformer$Capabilities_1_3_0_Translator.handleLayer(Capabilities_1_3_0_Transformer.java:979)
        at org.geoserver.wms.capabilities.Capabilities_1_3_0_Transformer$Capabilities_1_3_0_Translator.doHandleLayer(Capabilities_1_3_0_Transformer.java:877)
        ... 101 more
```

**Comment by jonescc** [comment]
Looks like there isn't a style for this layer which is the problem:

org.geoserver.platform.ServiceException: Could not find a style for layer imos:anmn_nrs_long_ts_interpolated_data, either none was specified or no default style is available for it

**Comment by lbesnard** [comment]
@jonescc actually I don't understand, becase this layer is a WFS one, so it does'nt need a style

**Comment by jonescc** [comment]
Its breaking the wms getcapabilities statement - I don't think there is a way to say this is just a WFS layer

**Comment by lbesnard** [comment]
@jonescc the other layer __anmn_nrs_long_ts_original_data__ is defined in the same way, i.e. doesn't have any style and doesn't break geoserver. So I don't really see what needs to be changed

**Comment by jonescc** [comment]
If I remove anmn_nrs_long_ts_interpolated_data  from my local vagrant instance I then get the same error with anmn_nrs_long_ts_original_data.   There may be more layers with issues as well

**Comment by jonescc** [comment]
Actually - GetCapabilities works if I remove those two layers.  So just need to fix those.

**Comment by lbesnard** [comment]
fixed here https://github.com/aodn/geoserver-config/pull/413
