### ISSUE TITLE
GeoServer Errors trying to render freemarker template for imos:soop_ba_trajectory_map

### ISSUE THREAD

**Issue by jonescc** [aodn/content#236]
ERROR [freemarker.runtime] - Template processing error: "Error reading imported file config.ftl"
Error reading imported file config.ftl
The problematic instruction:
----------
==> import "config.ftl" as my [on line 1, column 1 in content.ftl]
----------

Java backtrace for programmers:
----------
freemarker.template.TemplateException: Error reading imported file config.ftl
        at freemarker.core.LibraryLoad.accept(LibraryLoad.java:122)
        at freemarker.core.Environment.visit(Environment.java:221)
        at
ERROR [geoserver.ows] - 
java.io.IOException: Error occured processing content template content.ftl for imos:soop_ba_trajectory_map
        at org.geoserver.wms.featureinfo.HTMLFeatureInfoOutputFormat.write(HTMLFeatureInfoOutputFormat.java:138)
        at org.geoserver.wms.featureinfo.GetFeatureInfoResponse.write(GetFeatureInfoResponse.java:109)
        at org.geoserver.ows.Dispatcher.response(Dispatcher.java:996)
        at org.geoserver.ows.Dispatcher.handleRequestInternal(Dispatcher.java:279)
        at org.springframework.web

**Comment by jonescc** [comment]
Simmilar errors for imos:auv_tracks_vw as well

**Comment by bpasquer** [comment]
The layer is working fine on my VM.  I'll make a PR to fix the link to the charts, but again  it is not a generating an error when testing on VM.

**Comment by jonescc** [comment]
Definitely an error for this in the logs - I'll track down the exact request that caused it

**Comment by jonescc** [comment]
OK so it looks like its an intermittent error finding the config.ftl template - I'll move this to another repository.

**Comment by jonescc** [comment]
Thanks @bpasquer for looking at this - I've created https://github.com/aodn/aodn-portal/issues/2333 for developers to address occasionally missing config.ftl.
