### ISSUE TITLE
SRS ALTIMETRY - buggy pipeline, data loss and more

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#238]
The SRS ALTIMETRY pipeline/harvester is causing problems on both NEC14 and AWS10. Issues are different on both systems ... and the pipeline works wonderfully on the PO box (as a normal provision of a local artifact). 

## AWS10

on AWS, impossible to copy a file to the SRS ALTIMETRY pipeline.

For example 

[IMOS_SRSALT_PT_20140203T215000Z_BASJAS_FV01_SBE26d51m.nc.zip](https://github.com/aodn/content/files/532439/IMOS_SRSALT_PT_20140203T215000Z_BASJAS_FV01_SBE26d51m.nc.zip)

Run the following command to copy a SRS ALTIMETRY file into its INCOMING_DIR
```
wget https://github.com/aodn/content/files/532439/IMOS_SRSALT_PT_20140203T215000Z_BASJAS_FV01_SBE26d51m.nc.zip -O $DATA_SERVICES_TMP_DIR/temp.zip; unzip $DATA_SERVICES_TMP_DIR/temp.zip -d $INCOMING_DIR/SRS/ALTIMETRY; rm $DATA_SERVICES_TMP_DIR/temp.zip
```

input_logf SRS_ALTIMETRY
```
Oct 17 15:27:30 10-aws-syd SRS_ALTIMETRY: /usr/local/bin/watch-exec-wrapper.sh: line 60: /mnt/ebs/data-services/bin/false: No such file or directory
Oct 17 15:27:30 10-aws-syd SRS_ALTIMETRY: Could not process file 'File not handled':
Oct 17 15:27:30 10-aws-syd SRS_ALTIMETRY: Moving 'File not handled' -> '/mnt/ebs/error/SRS_ALTIMETRY/.20161017-152730'
Oct 17 15:27:30 10-aws-syd SRS_ALTIMETRY: Could not move 'File not handled' -> '/mnt/ebs/error/SRS_ALTIMETRY/.20161017-152730'
```

By the way, the __file disappears from the /mnt/ebs/error/SRS_ALTIMETRY folder and is completely lost__. At this stage, it shows how scary the data reconciliation could be.

## NEC14

Run the same commands above. The harvester will run and then break. 

log output example :
```
INFO 10/17/16 4:20 PM:liquibase: Successfully acquired change log lock
INFO 10/17/16 4:20 PM:liquibase: Reading from srs_altimetry.databasechangelog
INFO 10/17/16 4:20 PM:liquibase: Reading from srs_altimetry.databasechangelog
INFO 10/17/16 4:20 PM:liquibase: Successfully released change log lock
INFO 10/17/16 4:20 PM:liquibase: Successfully acquired change log lock
INFO 10/17/16 4:20 PM:liquibase: Reading from srs_altimetry.databasechangelog
INFO 10/17/16 4:20 PM:liquibase: Reading from srs_altimetry.databasechangelog
INFO 10/17/16 4:20 PM:liquibase: Successfully released change log lock
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in component iNetCDFInput_1
java.lang.NullPointerException
        at srs_altimetry.harvestfile_0_1.harvestFile.iNetCDFInput_1Process(harvestFile.java:3984)
        at srs_altimetry.harvestfile_0_1.harvestFile.iNetCDFGlobalAttributes_1Process(harvestFile.java:2735)
        at srs_altimetry.harvestfile_0_1.harvestFile.tPostgresqlInput_2Process(harvestFile.java:1026)
        at srs_altimetry.harvestfile_0_1.harvestFile.tPostgresqlConnection_1Process(harvestFile.java:698)
        at srs_altimetry.harvestfile_0_1.harvestFile.iIncludeSdiLibraries_1Process(harvestFile.java:580)
        at srs_altimetry.harvestfile_0_1.harvestFile.runJobInTOS(harvestFile.java:6634)
        at srs_altimetry.harvestfile_0_1.harvestFile.runJob(harvestFile.java:6489)
        at srs_altimetry.srs_altimetry_harvester_0_1.SRS_ALTIMETRY_harvester.iNewOrModifiedFileList_1Process(SRS_ALTIMETRY_harvester.java:2121)
        at srs_altimetry.srs_altimetry_harvester_0_1.SRS_ALTIMETRY_harvester.iDeletedFileList_1Process(SRS_ALTIMETRY_harvester.java:1904)
        at srs_altimetry.srs_altimetry_harvester_0_1.SRS_ALTIMETRY_harvester.iPostgresqlDbUpdate_1Process(SRS_ALTIMETRY_harvester.java:1577)
        at srs_altimetry.srs_altimetry_harvester_0_1.SRS_ALTIMETRY_harvester.iUpdateIndex_1Process(SRS_ALTIMETRY_harvester.java:1179)
        at srs_altimetry.srs_altimetry_harvester_0_1.SRS_ALTIMETRY_harvester.runJobInTOS(SRS_ALTIMETRY_harvester.java:4152)
        at srs_altimetry.srs_altimetry_harvester_0_1.SRS_ALTIMETRY_harvester.main(SRS_ALTIMETRY_harvester.java:3960)

```

It's seems a bit like a worry that the behavior is different on 3 systems

@aodn/emii-ops

**Comment by lwgordonimos** [comment]
@lbesnard It has not reloaded the queue handler since this change: https://github.com/aodn/data-services/blob/master/watch.d/SRS_ALTIMETRY.json

We can resolve this by restarting that queue manually. This is not ideal, but we had to modify the celery recipes in Chef to *not* restart the queue because it was sending a 'kill -9' to any running tasks and orphaning them, which was causing issues by allowing multiple concurrent harvesters (due to losing track of the orphan process). The alternative is to increase the time Chef will wait for the harvester to finish, but this is also bad because Chef can't just block and wait for a process, so there's not really a good.

The downside of this is that this happens when a watch is added/changed it needs a manual restart. This has been done on 10-aws-syd, so could you try that file again?

**Comment by lbesnard** [comment]
thanks, it works better. have another error now due to a view I cannot drop because it is used by an external schema for reporting ( @xhoenner could you please have a look) . The infrastructure/pipeline/... really needs some re-thinking

**Comment by julian1** [comment]
> By the way, the file disappears from the /mnt/ebs/error/SRS_ALTIMETRY folder and is completely lost. At this stage, it shows how scary the data reconciliation could be.

The scary bit is that "reconciliation" would *not* detect this, https://github.com/aodn/internal-discussions/issues/296
