### ISSUE TITLE
S3 connection lost over the weekend ??

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#281]
On 10-aws-syd there are a LOT of pipeline errors

I also checked the argo harvester which ran on Saturday
```bash

input_log 
Jun  4 07:10:30 10-aws-syd ARGO: branch found at:
Jun  4 07:10:30 10-aws-syd ARGO: https://github.com/s3tools/s3cmd
Jun  4 07:10:30 10-aws-syd ARGO: and have a look at the known issues list:
Jun  4 07:10:30 10-aws-syd ARGO: https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
Jun  4 07:10:30 10-aws-syd ARGO: If the error persists, please report the
Jun  4 07:10:30 10-aws-syd ARGO: following lines (removing any private
Jun  4 07:10:30 10-aws-syd ARGO: info as necessary) to:
Jun  4 07:10:30 10-aws-syd ARGO: s3tools-bugs@lists.sourceforge.net
Jun  4 07:10:31 10-aws-syd ARGO: Could not process file '/mnt/ebs/tmp/tmp.Ka5RNwj5Pg/argo_rsync.20170602-210545.log': Could not push to S3 '/mnt/ebs/wip/Argo/dac/jma/2902480/profiles/R2902480_117.nc' -> 's3://imos-data/IMOS/Argo/dac/jma/2902480/profiles/R2902480_117.nc'
Jun  4 07:10:31 10-aws-syd ARGO: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Jun  4 07:10:31 10-aws-syd ARGO: Invoked as: /usr/local/bin/s3cmd --config=/mnt/ebs/data-services/s3cfg -m application/octet-stream --no-preserve sync /mnt/ebs/wip/Argo/dac/jma/2902480/profiles/R2902480_117.nc s3://imos-data/IMOS/Argo/dac/jma/2902480/profiles/R2902480_117.nc
Jun  4 07:10:31 10-aws-syd ARGO: Problem: error: [Errno 104] Connection reset by peer
Jun  4 07:10:31 10-aws-syd ARGO: S3cmd:   1.6.0
Jun  4 07:10:31 10-aws-syd ARGO: python:   2.7.3 (default, Oct 26 2016, 21:01:49)
Jun  4 07:10:31 10-aws-syd ARGO: [GCC 4.6.3]
Jun  4 07:10:31 10-aws-syd ARGO: environment LANG=en_US.UTF-8
Jun  4 07:10:31 10-aws-syd ARGO: Moving '/mnt/ebs/tmp/tmp.Ka5RNwj5Pg/argo_rsync.20170602-210545.log' -> '/mnt/ebs/error/ARGO/argo_rsync.20170602-210545.log.20170602-210546'
Jun  4 07:10:31 10-aws-syd ARGO: Traceback (most recent call last):
Jun  4 07:10:31 10-aws-syd ARGO: File "/usr/local/bin/s3cmd", line 2805, in <module>
Jun  4 07:10:31 10-aws-syd ARGO: rc = main()
Jun  4 07:10:31 10-aws-syd ARGO: File "/usr/local/bin/s3cmd", line 2713, in main
Jun  4 07:10:31 10-aws-syd ARGO: rc = cmd_func(args)
Jun  4 07:10:31 10-aws-syd ARGO: File "/usr/local/bin/s3cmd", line 1666, in cmd_sync
Jun  4 07:10:31 10-aws-syd ARGO: return cmd_sync_local2remote(args)
Jun  4 07:10:31 10-aws-syd ARGO: File "/usr/local/bin/s3cmd", line 1644, in cmd_sync_local2remote
```

I don't think this is a good sign

@smancini @pblain @lwgordonimos

**Comment by lwgordonimos** [comment]
I can only find one instance of this particular error:

```
root@10-aws-syd:/mnt/ebs/log/data-services# zgrep 'Could not push to S3' process.log.?.gz process.log.1 process.log
process.log.1:Jun  4 07:10:31 10-aws-syd ARGO: Could not process file '/mnt/ebs/tmp/tmp.Ka5RNwj5Pg/argo_rsync.20170602-210545.log': Could not push to S3 '/mnt/ebs/wip/Argo/dac/jma/2902480/profiles/R2902480_117.nc' -> 's3://imos-data/IMOS/Argo/dac/jma/2902480/profiles/R2902480_117.nc'
```
The FAIMMS ones look different, since they are database related, so I suspect these are unrelated:

```Exception in component iUpdateIndex_1
java.lang.RuntimeException: liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by fe80:0:0:0:4b5:54ff:fe7c:a779%2 (fe80:0:0:0:4b5:54ff:fe7c:a779%2) since 5/26/17 2:58 AM
	at au.org.emii.talend.updateindex.FileIndexUpdater.runLiquibase(FileIndexUpdater.java:126)
	at au.org.emii.talend.updateindex.FileIndexUpdater.<init>(FileIndexUpdater.java:39)
	at au.org.emii.talend.updateindex.Component.run(Component.java:25)
	at faimms.faimms_harvester_0_1.FAIMMS_harvester.iUpdateIndex_1Process(FAIMMS_harvester.java:1157)
	at faimms.faimms_harvester_0_1.FAIMMS_harvester.runJobInTOS(FAIMMS_harvester.java:4659)
	at faimms.faimms_harvester_0_1.FAIMMS_harvester.main(FAIMMS_harvester.java:4467)
```

**Comment by lbesnard** [comment]
I'm suspect the FAIMMS one are actually similar. What probably happened is the harvester stopped running, maybe a connection lost for example, and a lock stayed in the database when LiquiBase ran. When this happens I always have to ask @julian1 to run a query on the database to unlock it

**Comment by lwgordonimos** [comment]
Ok makes sense. A temporary loss of connectivity outbound from 10-aws-syd may have caused both. Not sure how much we will be able to find, but will have a look...

**Comment by smancini** [comment]
Moved to the issue repository

**Comment by pblain** [comment]
@smancini - Leigh was looking into this. Wondering why you moved it?
