### ISSUE TITLE
Time subset on "Royal Australian Navy (RAN) - CTD profiles" doesn't work

### ISSUE THREAD

**Issue by jonescc** [aodn/content#346]
### To reproduce

On step 2 enter a temporal filter for this collection

### What happens 

Get an error loading the layer

### What I expect to happen

Layer is filtered by time range entered

**Comment by jonescc** [comment]
Looks like the temporal filters are configured incorrectly for this layer.  From the sumologic logs:

```
25 Jul 12:22:28 ERROR [geoserver.ows] - 
org.geoserver.wfs.WFSException: Illegal property name: time for feature type aodn:aodn_ran_ctd_map
	at org.geoserver.wfs.GetFeature$2.visit(GetFeature.java:1184)
	at org.geotools.filter.AttributeExpressionImpl.accept(AttributeExpressionImpl.java:340)
	at org.geotools.filter.visitor.AbstractFilterVisitor.visit(AbstractFilterVisitor.java:159)
	at org.geotools.filter.visitor.AbstractFilterVisitor.visit(AbstractFilterVisitor.java:208)
	at org.geotools.filter.IsGreaterThanOrEqualToImpl.accept(IsGreaterThanOrEqualToImpl.java:65)
	at org.geotools.filter.visitor.AbstractFilterVisitor.visit(AbstractFilterVisitor.java:324)
	at org.geotools.filter.visitor.AbstractFilterVisitor.visit(AbstractFilterVisitor.java:334)
	at org.geotools.filter.AndImpl.accept(AndImpl.java:52)
	at org.geoserver.wfs.GetFeature.validateFilter(GetFeature.java:1193)
```

**Comment by ggalibert** [comment]
Indeed, the Geoserver `aodn_ran_ctd_map` layer is based straight on the `aodn_ran_ctd_map` postgresql view which doesn't include any `time` field but `time_coverage_start` and `time_coverage_end`.

Either we modify the view to include a `time` field or we configure the Geoserver layer to use an sql view that includes a `time` field.

**Comment by mhidas** [comment]
It's the filters (on the corresponding _data layer) that are not configured correctly. In the [filters.xml](https://github.com/aodn/geoserver-config/blob/master/workspaces/aodn/JNDI_aodn_ran_ctd/aodn_ran_ctd_data/filters.xml) file, the time filter should look like this:
```xml
    <filter>
        <name>time</name>
        <type>datetime</type>
        <label>Time</label>
        <visualised>true</visualised>
        <excludedFromDownload>false</excludedFromDownload>
        <wmsStartDateName>time_coverage_start</wmsStartDateName>
        <wmsEndDateName>time_coverage_end</wmsEndDateName>
    </filter>
```

**Comment by ggalibert** [comment]
Thanks! I've just made a PR https://github.com/aodn/geoserver-config/pull/568 for this.

**Comment by ggalibert** [comment]
Now works on RC.

**Comment by ggalibert** [comment]
Did a geoserver_config_prod_merge so should be on prod this evening.
