### ISSUE TITLE
Harvests from CSIRO Geoserver failing with javax.net.ssl.SSLException: Received fatal alert: protocol_version

### ISSUE THREAD

**Issue by mhidas** [aodn/content#356]
This affects talend jobs **anmn_nrs_bgc** and **soop_auscpr**, both of which are running as cron jobs, and harvesting data from the [CSIRO Geoserver](https://www.cmar.csiro.au/geoserver/wfs?request=GetCapabilities) via WFS.

The full talend log looks like this:
```
begin;2018-08-02 18:00:04+10:00
Start of try block
tempFile_cid /tmp/talend-temp-211357261738893236/changelog.xml
***********************
conn host:dbprod.emii.org.au, port:5432, schema:anmn_nrs_bgc, name:harvest?loginTimeout=1000&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory, user:anmn_nrs_bgc
url_cid:jdbc:postgresql://dbprod.emii.org.au:5432/harvest?loginTimeout=1000&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
schema_cid:anmn_nrs_bgc
userName_cid:anmn_nrs_bgc
INFO 8/2/18 6:00 PM:liquibase: Successfully acquired change log lock
INFO 8/2/18 6:00 PM:liquibase: Reading from anmn_nrs_bgc.databasechangelog
INFO 8/2/18 6:00 PM:liquibase: Reading from anmn_nrs_bgc.databasechangelog
INFO 8/2/18 6:00 PM:liquibase: Successfully released change log lock
***** completed finally block ***********
In finally block
Exception in component sWfsInput_1_GI
javax.net.ssl.SSLException: Received fatal alert: protocol_version
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
        at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1991)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1098)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1344)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1371)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1302)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at org.geotools.data.wfs.protocol.http.SimpleHttpProtocol$SimpleHttpResponse.getResponseStream(SimpleHttpProtocol.java:70)
        at org.geotools.data.wfs.WFSDataStoreFactory.loadCapabilities(WFSDataStoreFactory.java:779)
        at org.geotools.data.wfs.WFSDataStoreFactory.createDataStore(WFSDataStoreFactory.java:412)
        at anmn_nrs_bgc.station_harvest_0_1.station_harvest.sWfsInput_1_GIProcess(station_harvest.java:2236)
        at anmn_nrs_bgc.station_harvest_0_1.station_harvest.tPostgresqlConnection_1Process(station_harvest.java:657)
        at anmn_nrs_bgc.station_harvest_0_1.station_harvest.iIncludeSdiLibraries_1Process(station_harvest.java:539)
        at anmn_nrs_bgc.station_harvest_0_1.station_harvest.runJobInTOS(station_harvest.java:4538)
        at anmn_nrs_bgc.station_harvest_0_1.station_harvest.runJob(station_harvest.java:4395)
        at anmn_nrs_bgc.anmn_nrs_bgc_harvester_0_1.ANMN_NRS_BGC_harvester.tRunJob_1Process(ANMN_NRS_BGC_harvester.java:2539)
        at anmn_nrs_bgc.anmn_nrs_bgc_harvester_0_1.ANMN_NRS_BGC_harvester.tPostgresqlClose_1Process(ANMN_NRS_BGC_harvester.java:2400)
        at anmn_nrs_bgc.anmn_nrs_bgc_harvester_0_1.ANMN_NRS_BGC_harvester.iPostgresqlDbUpdate_1Process(ANMN_NRS_BGC_harvester.java:2297)
        at anmn_nrs_bgc.anmn_nrs_bgc_harvester_0_1.ANMN_NRS_BGC_harvester.tPostgresqlConnection_1Process(ANMN_NRS_BGC_harvester.java:1551)
        at anmn_nrs_bgc.anmn_nrs_bgc_harvester_0_1.ANMN_NRS_BGC_harvester.iIncludeSdiLibraries_1Process(ANMN_NRS_BGC_harvester.java:1417)
        at anmn_nrs_bgc.anmn_nrs_bgc_harvester_0_1.ANMN_NRS_BGC_harvester.runJobInTOS(ANMN_NRS_BGC_harvester.java:5769)
        at anmn_nrs_bgc.anmn_nrs_bgc_harvester_0_1.ANMN_NRS_BGC_harvester.main(ANMN_NRS_BGC_harvester.java:5529)
Exception in component tRunJob_1
java.lang.RuntimeException: Child job running failed
        at anmn_nrs_bgc.anmn_nrs_bgc_harvester_0_1.ANMN_NRS_BGC_harvester.tRunJob_1Process(ANMN_NRS_BGC_harvester.java:2550)
        at anmn_nrs_bgc.anmn_nrs_bgc_harvester_0_1.ANMN_NRS_BGC_harvester.tPostgresqlClose_1Process(ANMN_NRS_BGC_harvester.java:2400)
        at anmn_nrs_bgc.anmn_nrs_bgc_harvester_0_1.ANMN_NRS_BGC_harvester.iPostgresqlDbUpdate_1Process(ANMN_NRS_BGC_harvester.java:2297)
        at anmn_nrs_bgc.anmn_nrs_bgc_harvester_0_1.ANMN_NRS_BGC_harvester.tPostgresqlConnection_1Process(ANMN_NRS_BGC_harvester.java:1551)
        at anmn_nrs_bgc.anmn_nrs_bgc_harvester_0_1.ANMN_NRS_BGC_harvester.iIncludeSdiLibraries_1Process(ANMN_NRS_BGC_harvester.java:1417)
        at anmn_nrs_bgc.anmn_nrs_bgc_harvester_0_1.ANMN_NRS_BGC_harvester.runJobInTOS(ANMN_NRS_BGC_harvester.java:5769)
        at anmn_nrs_bgc.anmn_nrs_bgc_harvester_0_1.ANMN_NRS_BGC_harvester.main(ANMN_NRS_BGC_harvester.java:5529)
finish;2018-08-02 18:00:07+10:00 0 minutes
```

**Comment by mhidas** [comment]
@aodn/emii-ops Any idea what this means?

If it's a problem on their end, I will contact the relevant people at CSIRO, but first it would be good to know what the problem is.

**Comment by lwgordonimos** [comment]
It doesn't appear to be an issue on their end, but they may have changed something on their side to break compatibility with our HTTP client, e.g. something like stopping supporting older TLS. Will dig more tomorrow...

**Comment by jonescc** [comment]
They've probably stopped supporting older versions of TLS for connections (e.g. by upgrading java).  Looks like they are requiring TLS 1.2 which older versions of  java 7 don't support by default.   This is happening on a lot of sites as older versions of TLS are insecure.    Options are: upgrading to java 8, setting older versions of java 7 to use TLS 1.2  by setting jdk.tls.client.protocol=TLSv1.2 (its compatible with older versions of TLS) or upgrading to java 1.7.0_131-b31 or later where TLSv1.2 and TLSV1.1 are enabled on client endpoints by default.

We should really be looking at upgrading to java8?

**Comment by jonescc** [comment]
Also see https://github.com/aodn/issues/issues/258

**Comment by lwgordonimos** [comment]
Thanks, I didn't see the other issue.

The only thing I would add is that I suspect it's not actually anything to do with Java on their side enforcing the protocol, but their load balancer terminating the HTTPS. Kind of a moot point, because ultimately the server and client just need to negotiate a mutually acceptable protocol regardless of the provider, but Java 8 isn't the solution to all the worlds problems, but it probably is the best solution for our HTTP client code ;)

**Comment by mhidas** [comment]
Thanks guys. So this is not really a content issue. Since https://github.com/aodn/issues/issues/258 essentially the same issue, we can close this here.
