### ISSUE TITLE
AUV harvester - liquibase issue on aws10

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#370]
```talend_liqui auv-auv``` on aws10 fails with liquibase

```
Exception in component iPostgresqlDbUpdate_4
liquibase.exception.MigrationFailedException: Migration failed for change set changelog.xml::2382580250144-14::talend:
     Reason: liquibase.exception.DatabaseException: Error executing SQL DROP VIEW IF EXISTS auv_trajectory_map: ERROR: cannot drop view auv_trajectory_map because other objects depend on it
  Detail: view reporting.auv_all_deployments_view depends on view auv_trajectory_map
view reporting.auv_data_summary_view depends on view reporting.auv_all_deployments_view
  Hint: Use DROP ... CASCADE to drop the dependent objects too.:
          Caused By: Error executing SQL DROP VIEW IF EXISTS auv_trajectory_map: ERROR: cannot drop view auv_trajectory_map because other objects depend on it
  Detail: view reporting.auv_all_deployments_view depends on view auv_trajectory_map
view reporting.auv_data_summary_view depends on view reporting.auv_all_deployments_view
  Hint: Use DROP ... CASCADE to drop the dependent objects too.:
          Caused By: ERROR: cannot drop view auv_trajectory_map because other objects depend on it
  Detail: view reporting.auv_all_deployments_view depends on view auv_trajectory_map
view reporting.auv_data_summary_view depends on view reporting.auv_all_deployments_view
  Hint: Use DROP ... CASCADE to drop the dependent objects too.
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:347)
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:27)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:58)
        at liquibase.Liquibase.update(Liquibase.java:114)
        at auv.auv_harvester_0_1.AUV_harvester.iPostgresqlDbUpdate_4Process(AUV_harvester.java:2148)
        at auv.auv_harvester_0_1.AUV_harvester.iPostgresqlDbUpdate_3Process(AUV_harvester.java:1901)
        at auv.auv_harvester_0_1.AUV_harvester.iPostgresqlDbUpdate_2Process(AUV_harvester.java:1659)
        at auv.auv_harvester_0_1.AUV_harvester.iUpdateIndex_1Process(AUV_harvester.java:1358)
        at auv.auv_harvester_0_1.AUV_harvester.iPostgresqlDbUpdate_1Process(AUV_harvester.java:1239)
        at auv.auv_harvester_0_1.AUV_harvester.runJobInTOS(AUV_harvester.java:4995)
        at auv.auv_harvester_0_1.AUV_harvester.main(AUV_harvester.java:4831)
Caused by: liquibase.exception.DatabaseException: Error executing SQL DROP VIEW IF EXISTS auv_trajectory_map: ERROR: cannot drop view auv_trajectory_map because other objects depend on it
  Detail: view reporting.auv_all_deployments_view depends on view auv_trajectory_map
view reporting.auv_data_summary_view depends on view reporting.auv_all_deployments_view
  Hint: Use DROP ... CASCADE to drop the dependent objects too.
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:62)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:104)
        at liquibase.database.AbstractDatabase.execute(AbstractDatabase.java:1091)
        at liquibase.database.AbstractDatabase.executeStatements(AbstractDatabase.java:1075)
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:317)
        ... 10 more
Caused by: org.postgresql.util.PSQLException: ERROR: cannot drop view auv_trajectory_map because other objects depend on it
  Detail: view reporting.auv_all_deployments_view depends on view auv_trajectory_map
view reporting.auv_data_summary_view depends on view reporting.auv_all_deployments_view
  Hint: Use DROP ... CASCADE to drop the dependent objects too.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2157)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1886)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:555)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:403)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:395)
        at liquibase.executor.jvm.JdbcExecutor$1ExecuteStatementCallback.doInStatement(JdbcExecutor.java:92)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
        ... 14 more
2018-08-30 17:48:32;cIORtA;cIORtA;cIORtA;10131;AUV;AUV_harvester;_-H3_wEsvEeOpS4EfPHUwwQ;0.1;Default;;begin;;

2018-08-30 17:48:34;cIORtA;cIORtA;cIORtA;10131;AUV;AUV_harvester;_-H3_wEsvEeOpS4EfPHUwwQ;0.1;Default;;end;failure;1816

Talend harvester auv-auv: 1 file(s)  FAILED
Aborting operation
```

need to fix

**Comment by lbesnard** [comment]
@xhoenner could you drop reporting.auv_all_deployments_view depends ? so I can run my query ?

**Comment by xhoenner** [comment]
I dropped that view @lbesnard, see whether it resolves this issue.
