### ISSUE TITLE
GetFeatureInfo failing for for auv_trajectory_map

### ISSUE THREAD

**Issue by jonescc** [aodn/content#371]
From the geoserver logs

```
Failed to execute statement SELECT "file_id","url","size","campaign_name","dive_name","time_coverage_start","time_coverage_end","colour","CDOM_b","CPHL_b","OPBS_b","PSAL_b","TEMP_b",encode(ST_AsBinary(CASE WHEN ST_HasArc("geom") THEN "geom" ELSE ST_Simplify(ST_Force2D("geom"), 1.3732905297274557E-4, true) END),'base64') as "geom" FROM "auv"."auv_trajectory_map" WHERE  "geom" && ST_GeomFromText('POLYGON ((115.70351221538459 -32.046540125200636, 115.70351221538459 -32.03418051043339, 115.71587184615383 -32.03418051043339, 115.71587184615383 -32.046540125200636, 115.70351221538459 -32.046540125200636))', 4326)
...
Caused by: java.sql.SQLException: org.postgresql.util.PSQLException: ERROR: column "CDOM_b" does not exist
  Position: 110
	at org.geotools.jdbc.JDBCFeatureReader.<init>(JDBCFeatureReader.java:155)
	at org.geotools.jdbc.JDBCFeatureSource.getReaderInternal(JDBCFeatureSource.java:619)
	... 119 more
```

**Comment by ggalibert** [comment]
Does the problem still exist @jonescc ?

**Comment by jonescc** [comment]
No.  Looks to have been resolved.
