### ISSUE TITLE
National Wave archive Health bad -read timed out

### ISSUE THREAD

**Issue by bpasquer** [aodn/content#394]
The National wave archive collection is in bad health.
Not quite sure what has to be done to fix it.
Sumologic output the following error 
`[WFS GetFeature request results in exception for uuid='2807f3aa-4db0-4924-b64b-354ae8c10b58', url='http://geoserver-portal-internal.aodn.org.au/geoserver/ows?service=WFS&version=1.0.0&request=GetFeature&maxFeatures=1&outputFormat=csv&typeName=aodn:aodn_wave_dm_timeseries_data', error='Read timed out' stack='
java.net.SocketTimeoutException: Read timed out
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
at java.net.SocketInputStream.read(SocketInputStream.java:171)
at java.net.SocketInputStream.read(SocketInputStream.java:141)
at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
at org.fao.geonet.monitor.onlineresource.OnlineResourceCheckerWfs.check(OnlineResourceCheckerWfs.java:36)
at org.fao.geonet.monitor.onlineresource.CheckInfo.<init>(http://CheckInfo.java:9)
at org.fao.geonet.monitor.onlineresource.OnlineResourceInfo.check(OnlineResourceInfo.java:93)
at org.fao.geonet.monitor.onlineresource.MetadataRecordInfo.check(MetadataRecordInfo.java:117)
at org.fao.geonet.monitor.onlineresource.OnlineResourceMonitorService.check(OnlineResourceMonitorService.java:227)
at org.fao.geonet.monitor.onlineresource.OnlineResourceMonitorService.run(OnlineResourceMonitorService.java:106)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
']`

**Comment by ggalibert** [comment]
Fixed by https://github.com/aodn/geoserver-config/pull/590/files
