### ISSUE TITLE
AIMS_MMP_CTD pipeline configured to non-existent incoming dir

### ISSUE THREAD

**Issue by mhidas** [aodn/content#495]
From `/mnt/ebs/log/pipeline/watchservice/pipeline_watchservice-stderr.log` on 4-nec-hob:
```
Traceback (most recent call last):
  File "/mnt/ebs/pyenv/versions/3.5.2/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/mnt/ebs/pyenv/versions/3.5.2/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/ebs/pyenv/versions/pipeline_rc_venv/lib/python3.5/site-packages/aodncore/pipeline/watchservice.py", line 29, in <module>
    main()
  File "/mnt/ebs/pyenv/versions/pipeline_rc_venv/lib/python3.5/site-packages/aodncore/pipeline/watchservice.py", line 18, in main
    with WatchServiceManager(CONFIG, context.event_handler, context.watch_manager, context.notifier) as watch_manager:
  File "/mnt/ebs/pyenv/versions/pipeline_rc_venv/lib/python3.5/site-packages/aodncore/pipeline/watch.py", line 561, in __enter__
    self._queue_and_watch_directories()
  File "/mnt/ebs/pyenv/versions/pipeline_rc_venv/lib/python3.5/site-packages/aodncore/pipeline/watch.py", line 573, in _queue_and_watch_directories
    for existing_file in list_regular_files(directory):
  File "/mnt/ebs/pyenv/versions/pipeline_rc_venv/lib/python3.5/site-packages/aodncore/util/fileops.py", line 254, in list_regular_files
    return inner_func(path)
  File "/mnt/ebs/pyenv/versions/pipeline_rc_venv/lib/python3.5/site-packages/aodncore/util/fileops.py", line 241, in nonrecursive_list
    dir_entries = sorted(os.scandir(os.path.abspath(path_)), key=lambda p: sort_key(p.name))
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/ebs/incoming/AIMS/MMP_CTD'
```

Looks like the `path` specified in the [watch config](https://github.com/aodn/chef-private/blob/744f0c64ddc04f17b732608ab09e785e117b5b39/data_bags/imos_po_watches/AIMS_MMP_CTD.json#L3) doesn't match the directory created in [ftp_dir_tree](https://github.com/aodn/chef-private/blob/744f0c64ddc04f17b732608ab09e785e117b5b39/data_bags/ftp_dir_tree/AIMS.json#L5)

**Comment by ggalibert** [comment]
@lbesnard @mhidas can we close this?
