### ISSUE TITLE
Moorings hourly product generation fails for NRSYON site

### ISSUE THREAD

**Issue by mhidas** [aodn/content#521]
This issue first occurred on 2024-08-18

e.g. `tasks.MOORINGS_PRODUCTS[c3f46cc2-885a-4391-809b-a510474b0485]` (2024-09-01 04:42)
```
Traceback (most recent call last):
  File "/mnt/ebs/pyenv/versions/3.8.13/envs/pipeline_prod_venv/lib/python3.8/site-packages/xarray/core/dataset.py", line 1394, in _construct_dataarray
    variable = self._variables[name]
KeyError: 'Dire'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/ebs/pyenv/versions/3.8.13/envs/pipeline_prod_venv/lib/python3.8/site-packages/aodncore/pipeline/handlerbase.py", line 1054, in run
    self.trigger(transition['trigger'])
  File "/mnt/ebs/pyenv/versions/3.8.13/envs/pipeline_prod_venv/lib/python3.8/site-packages/transitions/core.py", line 899, in _get_trigger
    return event.trigger(model, *args, **kwargs)
  File "/mnt/ebs/pyenv/versions/3.8.13/envs/pipeline_prod_venv/lib/python3.8/site-packages/transitions/core.py", line 401, in trigger
    return self.machine._process(func)
  File "/mnt/ebs/pyenv/versions/3.8.13/envs/pipeline_prod_venv/lib/python3.8/site-packages/transitions/core.py", line 1188, in _process
    return trigger()
  File "/mnt/ebs/pyenv/versions/3.8.13/envs/pipeline_prod_venv/lib/python3.8/site-packages/transitions/core.py", line 426, in _trigger
    return self._process(event_data)
  File "/mnt/ebs/pyenv/versions/3.8.13/envs/pipeline_prod_venv/lib/python3.8/site-packages/transitions/core.py", line 435, in _process
    if trans.execute(event_data):
  File "/mnt/ebs/pyenv/versions/3.8.13/envs/pipeline_prod_venv/lib/python3.8/site-packages/transitions/core.py", line 272, in execute
    event_data.machine.callbacks(itertools.chain(event_data.machine.before_state_change, self.before), event_data)
  File "/mnt/ebs/pyenv/versions/3.8.13/envs/pipeline_prod_venv/lib/python3.8/site-packages/transitions/core.py", line 1123, in callbacks
    self.callback(func, event_data)
  File "/mnt/ebs/pyenv/versions/3.8.13/envs/pipeline_prod_venv/lib/python3.8/site-packages/transitions/core.py", line 1144, in callback
    func(*event_data.args, **event_data.kwargs)
  File "/mnt/ebs/pyenv/versions/3.8.13/envs/pipeline_prod_venv/lib/python3.8/site-packages/aodndata/moorings/products_handler.py", line 390, in preprocess
    self._make_hourly_timeseries()
  File "/mnt/ebs/pyenv/versions/3.8.13/envs/pipeline_prod_venv/lib/python3.8/site-packages/aodndata/moorings/products_handler.py", line 299, in _make_hourly_timeseries
    product_url, errors = hourly_aggregator(input_list, self.product_site_code, qc_flags,
  File "/mnt/ebs/pyenv/versions/3.8.13/envs/pipeline_prod_venv/lib/python3.8/site-packages/aodntools/timeseries_products/hourly_timeseries.py", line 400, in hourly_aggregator
    nc_clean = good_data_only(nc_clean, qcflags)  # good quality data only
  File "/mnt/ebs/pyenv/versions/3.8.13/envs/pipeline_prod_venv/lib/python3.8/site-packages/aodntools/timeseries_products/hourly_timeseries.py", line 79, in good_data_only
    nc_masked[variable] = nc[variable].where(nc[variable + '_quality_control'].isin(qcflags))
  File "/mnt/ebs/pyenv/versions/3.8.13/envs/pipeline_prod_venv/lib/python3.8/site-packages/xarray/core/dataset.py", line 1498, in __getitem__
    return self._construct_dataarray(key)
  File "/mnt/ebs/pyenv/versions/3.8.13/envs/pipeline_prod_venv/lib/python3.8/site-packages/xarray/core/dataset.py", line 1396, in _construct_dataarray
    _, name, variable = _get_virtual_variable(
  File "/mnt/ebs/pyenv/versions/3.8.13/envs/pipeline_prod_venv/lib/python3.8/site-packages/xarray/core/dataset.py", line 169, in _get_virtual_variable
    ref_var = variables[ref_name]
KeyError: 'Dire'
```

**Comment by mphemming** [comment]
I have added the hourly product at this site as one to skip as part of https://github.com/aodn/PO-Backlog/issues/3935
