### ISSUE TITLE
talend anmn_nrs_ctd_profiles failing

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#80]
Failing on files:
```
/mnt/imos-t3/IMOS/opendap/ANMN/NRS/NRSROT/Biogeochem_profiles/IMOS_ANMN-NRS_CDEKOSTUZ_20100820T063200Z_NRSROT_FV01_3018.0-1-SBE19plus-40_C-20140130T092001Z.nc
/mnt/imos-t3/IMOS/opendap/ANMN/NRS/NRSROT/Biogeochem_profiles/IMOS_ANMN-NRS_CDEKOSTUZ_20100617T060500Z_NRSROT_FV01_3016.0-1-SBE19plus-41_C-20140130T091937Z.nc
/mnt/imos-t3/IMOS/opendap/ANMN/NRS/NRSROT/Biogeochem_profiles/IMOS_ANMN-NRS_CDEKOSTUZ_20100723T040200Z_NRSROT_FV01_3017.0-1-SBE19plus-46_C-20140130T091949Z.nc
/mnt/imos-t3/IMOS/opendap/ANMN/NRS/NRSROT/Biogeochem_profiles/IMOS_ANMN-NRS_CDEKOSTUZ_20100520T020500Z_NRSROT_FV01_3015.0-1-SBE19plus-45_C-20140130T091925Z.nc
```

With the following errors:
```
Exception while processing /mnt/imos-t3/IMOS/opendap/ANMN/NRS/NRSROT/Biogeochem_profiles/IMOS_ANMN-NRS_CDEKOSTUZ_20100520T020500Z_NRSROT_FV01_3015.0-1-SBE19plus-45_C-20140130T091925Z.nc
java.lang.NullPointerException
        at anmn_nrs_ctd_profiles.dataharvest_0_1.DataHarvest.iDeletedResources_1Process(DataHarvest.java:1477)
        at anmn_nrs_ctd_profiles.dataharvest_0_1.DataHarvest.iPostgresqlDbUpdate_1Process(DataHarvest.java:1326)
        at anmn_nrs_ctd_profiles.dataharvest_0_1.DataHarvest.runJobInTOS(DataHarvest.java:3698)
        at anmn_nrs_ctd_profiles.dataharvest_0_1.DataHarvest.runJob(DataHarvest.java:3526)
        at anmn_nrs_ctd_profiles.anmn_nrs_ctd_profiles_harvester_0_1.ANMN_NRS_CTD_PROFILES_harvester.tRunJob_2Process(ANMN_NRS_CTD_PROFILES_harvester.java:1319)
        at anmn_nrs_ctd_profiles.anmn_nrs_ctd_profiles_harvester_0_1.ANMN_NRS_CTD_PROFILES_harvester.tRunJob_1Process(ANMN_NRS_CTD_PROFILES_harvester.java:1202)
        at anmn_nrs_ctd_profiles.anmn_nrs_ctd_profiles_harvester_0_1.ANMN_NRS_CTD_PROFILES_harvester.runJobInTOS(ANMN_NRS_CTD_PROFILES_harvester.java:3281)
        at anmn_nrs_ctd_profiles.anmn_nrs_ctd_profiles_harvester_0_1.ANMN_NRS_CTD_PROFILES_harvester.main(ANMN_NRS_CTD_PROFILES_harvester.java:3085)
```

**Comment by mhidas** [comment]
@danfruehauf  I've reported this as https://github.com/aodn/harvesters/issues/182, but you're probably right that it's a content issue. The harvester was fine until these files came along. I've had a bit of a look and so far I haven't been able to work out what's wrong with them.

Any of you java gurus want to comment on what a "NullPointerException" might imply?

**Comment by danfruehauf** [comment]
I wasn't aware. Good you created a link.

Perhaps one of the devs can pair with you on that. It's probably talend trying to parse a value that's not there.

**Comment by mhidas** [comment]
Craig has spotted the problem... it was a harvester bug. https://github.com/aodn/harvesters/pull/212 should fix it.

**Comment by danfruehauf** [comment]
Would you like me to promote it to RC and then to production?

**Comment by mhidas** [comment]
@danfruehauf  It hasn't been merged yet, and it needs to be tested. I haven't actually run it yet because I don't have the PO VM set up. I guess we could just test it in on RC?

**Comment by danfruehauf** [comment]
RC is for that. Get it merged, I'll deploy it.
