### ISSUE TITLE
talend soop_auscpr failing

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#85]
Log snippet:
```
Source CRS is: GEOGCS["WGS 84", 
  DATUM["World Geodetic System 1984", 
    SPHEROID["WGS 84", 6378137.0, 298.257223563, AUTHORITY["EPSG","7030"]], 
    AUTHORITY["EPSG","6326"]], 
  PRIMEM["Greenwich", 0.0, AUTHORITY["EPSG","8901"]], 
  UNIT["degree", 0.017453292519943295], 
  AXIS["Geodetic latitude", NORTH], 
  AXIS["Geodetic longitude", EAST], 
  AUTHORITY["EPSG","4326"]]
Request: https://www.cmar.csiro.au/geoserver/wfs?SERVICE=WFS&VERSION=1.1.0&REQUEST=GetFeature&TYPENAME=imos:AUSCPR_ZOOP&PROPERTYNAME=ACKNOWLEDGEMENTS,TAXON_NAME,LATITUDE,TAXON_GROUP,START_PORT,SEX,ROUTE_START_DATE,VESSEL_NAME,MID_PT,TRIP_CODE,ROUTE_CODE,TIME_UTC,TAXON_ECO_GROUP,ZOOP_COMMENTS,GENUS,FAMILY,TAXON_PER_M3,CAAB_CODE,ROUTE_FREQUENCY,END_PORT,SPECIES,TAXON_START_DATE,LONGITUDE,LIFE_STAGE&SRSNAME=EPSG:4326&
Exception in component tMap_1
java.lang.NullPointerException
        at soop_auscpr.zoop_harvest_0_1.zoop_harvest.sWfsInput_1_GIProcess(zoop_harvest.java:3602)
        at soop_auscpr.zoop_harvest_0_1.zoop_harvest.iPostgresqlDbUpdate_1Process(zoop_harvest.java:822)
        at soop_auscpr.zoop_harvest_0_1.zoop_harvest.tPostgresqlConnection_1Process(zoop_harvest.java:598)
        at soop_auscpr.zoop_harvest_0_1.zoop_harvest.iIncludeSdiLibraries_1Process(zoop_harvest.java:480)
        at soop_auscpr.zoop_harvest_0_1.zoop_harvest.runJobInTOS(zoop_harvest.java:4220)
        at soop_auscpr.zoop_harvest_0_1.zoop_harvest.runJob(zoop_harvest.java:4091)
        at soop_auscpr.soop_auscpr_harvester_0_1.SOOP_AUSCPR_harvester.tRunJob_5Process(SOOP_AUSCPR_harvester.java:1311)
        at soop_auscpr.soop_auscpr_harvester_0_1.SOOP_AUSCPR_harvester.runJobInTOS(SOOP_AUSCPR_harvester.java:3087)
        at soop_auscpr.soop_auscpr_harvester_0_1.SOOP_AUSCPR_harvester.main(SOOP_AUSCPR_harvester.java:2909)
Exception in component tRunJob_5
java.lang.RuntimeException: Child job running failed
        at soop_auscpr.soop_auscpr_harvester_0_1.SOOP_AUSCPR_harvester.tRunJob_5Process(SOOP_AUSCPR_harvester.java:1322)
        at soop_auscpr.soop_auscpr_harvester_0_1.SOOP_AUSCPR_harvester.runJobInTOS(SOOP_AUSCPR_harvester.java:3087)
        at soop_auscpr.soop_auscpr_harvester_0_1.SOOP_AUSCPR_harvester.main(SOOP_AUSCPR_harvester.java:2909)
finish;2015-03-26 20:02:26+11:00 2 minutes
```

**Comment by mhidas** [comment]
This is due to Null values in the TAXON_START_DATE column of AUSCPR_ZOOP table (similar to https://github.com/aodn/harvesters/issues/204). Hopefully they will fix it at their end, otherwise we'll have to update the harvester to handle Nulls in that column.

**Comment by mhidas** [comment]
@smancini I haven't heard back from Claire or Margaret about this, but you were copied on the email, so when they reply, please update this issue.

**Comment by kereid** [comment]
Looks like this might be causing an issue on the portal, for the AusCPR Zooplankton layer - the Hesperides vessel is missing from the list. But it is still available for Phytoplankton and PCI

**Comment by lbesnard** [comment]
should be fixed here  https://github.com/aodn/harvesters/commit/a17cab6866d9c63c22ed1eebecdd6abb3d8fd04c

harvester failed because of many many things

running now sucessfully on RC
