### ISSUE TITLE
talend gsla_dm00 failing

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#90]
A snippet from the log:
```
 Message: Batch entry 0 INSERT INTO "gsla_dm00"."timeseries" ("file_id","time") VALUES (4495,2014-02-05 11:00:00.000000 +1100) was aborted.  Call getN
extException to see the cause.
 SQLSTATE: null
 Error code: 0
 Stacktrace:java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "gsla_dm00"."timeseries" ("file_id","time") VALUES (4495,2014-02-05 11:00:00.000000 +1100) was aborted.  Call getNextException to see the cause.
        at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2512)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1310)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:347)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2574)
        at gsla_dm00.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.iNetCDFInput_1Process(HarvestTimeseriesFile.java:1593)
        at gsla_dm00.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.tPostgresqlRow_1Process(HarvestTimeseriesFile.java:822)
        at gsla_dm00.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.tPostgresqlConnection_1Process(HarvestTimeseriesFile.java:693)
        at gsla_dm00.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.iIncludeSdiLibraries_1Process(HarvestTimeseriesFile.java:570)
        at gsla_dm00.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.runJobInTOS(HarvestTimeseriesFile.java:3846)
        at gsla_dm00.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.runJob(HarvestTimeseriesFile.java:3695)
        at gsla_dm00.gsla_dm00_harvester_1_0.GSLA_DM00_harvester.iHarvestResources_1Process(GSLA_DM00_harvester.java:2018)
        at gsla_dm00.gsla_dm00_harvester_1_0.GSLA_DM00_harvester.iDeletedResources_1Process(GSLA_DM00_harvester.java:1523)
        at gsla_dm00.gsla_dm00_harvester_1_0.GSLA_DM00_harvester.iPostgresqlDbUpdate_1Process(GSLA_DM00_harvester.java:1207)
        at gsla_dm00.gsla_dm00_harvester_1_0.GSLA_DM00_harvester.iIndexFiles_1_iFilesProcess(GSLA_DM00_harvester.java:2775)
        at gsla_dm00.gsla_dm00_harvester_1_0.GSLA_DM00_harvester.runJobInTOS(GSLA_DM00_harvester.java:4499)
        at gsla_dm00.gsla_dm00_harvester_1_0.GSLA_DM00_harvester.main(GSLA_DM00_harvester.java:4327)

SQL exception:
 Message: ERROR: duplicate key value violates unique constraint "timeseries_uc"
  Detail: Key ("time")=(2014-02-05 00:00:00+00) already exists.
 SQLSTATE: 23505
 Error code: 0
 Stacktrace:org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "timeseries_uc"
  Detail: Key ("time")=(2014-02-05 00:00:00+00) already exists.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:1525)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1309)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:347)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2574)
        at gsla_dm00.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.iNetCDFInput_1Process(HarvestTimeseriesFile.java:1593)
        at gsla_dm00.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.tPostgresqlRow_1Process(HarvestTimeseriesFile.java:822)
        at gsla_dm00.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.tPostgresqlConnection_1Process(HarvestTimeseriesFile.java:693)
        at gsla_dm00.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.iIncludeSdiLibraries_1Process(HarvestTimeseriesFile.java:570)
        at gsla_dm00.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.runJobInTOS(HarvestTimeseriesFile.java:3846)
        at gsla_dm00.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.runJob(HarvestTimeseriesFile.java:3695)
        at gsla_dm00.gsla_dm00_harvester_1_0.GSLA_DM00_harvester.iHarvestResources_1Process(GSLA_DM00_harvester.java:2018)
        at gsla_dm00.gsla_dm00_harvester_1_0.GSLA_DM00_harvester.iDeletedResources_1Process(GSLA_DM00_harvester.java:1523)
        at gsla_dm00.gsla_dm00_harvester_1_0.GSLA_DM00_harvester.iPostgresqlDbUpdate_1Process(GSLA_DM00_harvester.java:1207)
        at gsla_dm00.gsla_dm00_harvester_1_0.GSLA_DM00_harvester.iIndexFiles_1_iFilesProcess(GSLA_DM00_harvester.java:2775)
        at gsla_dm00.gsla_dm00_harvester_1_0.GSLA_DM00_harvester.runJobInTOS(GSLA_DM00_harvester.java:4499)
        at gsla_dm00.gsla_dm00_harvester_1_0.GSLA_DM00_harvester.main(GSLA_DM00_harvester.java:4327)
```

**Comment by ggalibert** [comment]
Wrong log @danfruehauf , you seem to have copied/pasted some log from SOOP_AUSCPR instead of GSLA...

Looking at the GSLA logs, the error is about duplicates :
```
SQL exception:
 Message: ERROR: duplicate key value violates unique constraint "timeseries_uc"
  Detail: Key ("time")=(2014-02-05 00:00:00+00) already exists.
...
Exception while processing /mnt/imos-t3/IMOS/opendap/OceanCurrent/GSLA/DM00/2014/IMOS_OceanCurrent_HV_20140205T000000Z_GSLA_FV02_DM00_C-20150109T100355Z.nc.gz
```

I'll have a look at that. Seems like a whole bunch of files are found as duplicates recently.

**Comment by danfruehauf** [comment]
Yep, my bad. I'll fix it in the original posting.

**Comment by ggalibert** [comment]
Duplicates have been removed from Opendap but logs are still showing errors due to duplicates. Looks like the iDeleteRessources is not happening for some reason. Need to investigate further with @julian1 and @jonescc
