### ISSUE TITLE
talend soop_tmv_nrt

### ISSUE THREAD

**Issue by xhoenner** [aodn/content#99]
Harvester failing on 9-nsp due to a privilege issue, see copy of the log below. Looks like the owner of the files changes between files. Could you investigate @danfruehauf? 

```
Exception while processing /mnt/ebs/talend/data/soop_tmv_nrt/zipped/EPA_SOOP_TMV1_M2D_20150505100850.log.1SecRaw.zip
java.io.FileNotFoundException: /mnt/imos-t4/IMOS/public/SOOP/TMV/VLST_Spirit-of-Tasmania-1/realtime/transect/1sec/EPA_SOOP_TMV1_M2D_20150505100850.log.1SecRaw.log (Permission denied)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
        at soop_tmv_nrt.copy_data_to_public_0_1.Copy_data_to_public$1Util_tFileUnarchive_5.output(Copy_data_to_public.java:1389)
        at soop_tmv_nrt.copy_data_to_public_0_1.Copy_data_to_public.iHarvestResources_4Process(Copy_data_to_public.java:1510)
        at soop_tmv_nrt.copy_data_to_public_0_1.Copy_data_to_public.iIndexFiles_4_iFilesProcess(Copy_data_to_public.java:5692)
        at soop_tmv_nrt.copy_data_to_public_0_1.Copy_data_to_public.iIndexFiles_3_iFilesProcess(Copy_data_to_public.java:5066)
        at soop_tmv_nrt.copy_data_to_public_0_1.Copy_data_to_public.iIndexFiles_2_iFilesProcess(Copy_data_to_public.java:4446)
        at soop_tmv_nrt.copy_data_to_public_0_1.Copy_data_to_public.iIndexFiles_1_iFilesProcess(Copy_data_to_public.java:3820)
        at soop_tmv_nrt.copy_data_to_public_0_1.Copy_data_to_public.runJobInTOS(Copy_data_to_public.java:5963)
        at soop_tmv_nrt.copy_data_to_public_0_1.Copy_data_to_public.runJob(Copy_data_to_public.java:5754)
        at soop_tmv_nrt.soop_tmv_nrt_harvester_0_1.SOOP_TMV_NRT_harvester.tRunJob_4Process(SOOP_TMV_NRT_harvester.java:1653)
        at soop_tmv_nrt.soop_tmv_nrt_harvester_0_1.SOOP_TMV_NRT_harvester.tSystem_2Process(SOOP_TMV_NRT_harvester.java:1515)
        at soop_tmv_nrt.soop_tmv_nrt_harvester_0_1.SOOP_TMV_NRT_harvester.runJobInTOS(SOOP_TMV_NRT_harvester.java:5286)
        at soop_tmv_nrt.soop_tmv_nrt_harvester_0_1.SOOP_TMV_NRT_harvester.main(SOOP_TMV_NRT_harvester.java:5022)
```

**Comment by danfruehauf** [comment]
This is due to the rebuild of 9-nsp-mel and the `talend` user changing UID. I recommended @xhoenner to create the files with permissions of `0666`, so the harvester is more "permissions agnostic". However it is not really necessary.

**Comment by danfruehauf** [comment]
Just `chown -R talend:talend` all the relevant files. Hope this fixes the problem.

**Comment by danfruehauf** [comment]
Ran harvester, no problems found.

**Comment by xhoenner** [comment]
Great, GJ @danfruehauf !

**Comment by danfruehauf** [comment]
GJ to you, for noticing that and seeking to fix that!
